vuejs/vue

src/directives/repeat.js
test/unit/specs/directives/repeat_spec.js

Fixes https://github.com/yyx990803/vue/issues/707

fix #707: v-repeat nested repeats on object

---

src/directives/model/default.js

jQuery have a lot of UI components，such as bootstrap-datepicker, select2, these components will change value of form control and won't trigger native change event. instead of,  these components trigger a internal jQuery change event, so we can listen jQuery change event in Vue for ViewModel

support jQuery change event

---

src/filters/index.js
test/unit/specs/filters/filters_spec.js

This PR fixes two issues in currency filter (demo for both: http://jsfiddle.net/k5bv3r62/ ):
1) x.999 values are shown as $x.00
Say you have model with value 0.999. With currency filter applied it will be shown as $0.00
2) Infinity value show as $In,finity.ty
I think, it would be good to return empty string as for falsy values
Also I added new test cases for described issues.

Return empty string for Infinity and properly format values such as 0.999

---

src/directives/model/select.js
test/unit/specs/directives/model_spec.js

I found a problem that initial value of v-model of <select> is treated as undefined if contains <option value="" selected>.
This fix, <option value="" selected> is treated as default value.

fix <option value="" selected> is undefined

---

src/util/dom.js

This fixes the issue with phantom.js not supporting document.documentElement.contains properly causing unit / integration tests to fail.

change inDoc function to work properly in phantom.js

---

src/util/lang.js

Carried over from #772 - change made on dev branch as requested.

Allow isReserved() to handle non-string inputs

---

src/directives/repeat.js
test/unit/specs/directives/repeat_spec.js

When the parent vm is reused, newly created children will inherit
the _reused property, and they won't be inserted into the dom.
Fixes #782

Fix nested repeats with track-by.

---

src/directives/events.js
test/unit/specs/directives/events_spec.js

This is a tentative implementation... It allows to use metaproperties like $index, $key in the handler without the child vm having to know about them.

let v-events accept statements

---

src/transition/css.js

jshint is not the only js linter, I got warnings from UglifyJS for example.

Prevent unused variable warning from all linters

---

src/directives/model/select.js
test/unit/specs/directives/model_spec.js

This PR adds support for an optional `disabled` setting in an `options` array for dynamic `<select>` elements.
Local tests ran fine, but Saucelabs choked so I wasn't able to test full browser compatibility. I'm worried that the `disabled=""` test isn't going to be consistent across browsers.

Support `disabled` attribute on select options

---

src/directives/attr.js
test/unit/specs/directives/attr_spec.js

The goal is to add to ``v-attr`` directive support for objects:
```
<div v-attr="obj"></div>
```
Demo here: http://jsfiddle.net/nd9baygn/3/
Waiting for suggestions patiently :)

Add objects support to v-attr

---

src/directives/repeat.js

While writing a drag and drop vue sortable directive which uses jQuery UI sortable (both same list and connected list sortable), I found vue was throwing `el` undefined errors a lot with various actions, e.g. dragging the first item in a list then updating the underlying array model. The element had been removed by jQuery while vue was expecting it to exist.
By checking for the existance of `el`, and returning and empty object if it does not exist, allow these two dom manipulation libraries play nicely together.

Cater for possibility of el not existing

---

dist/vue.js
src/transition/index.js

Consider `@oaram` tag in file __/src/transition/index.js__ typo of `@param`.

fix doc tag typo

---

CONTRIBUTING.md
src/filters/index.js
test/unit/specs/filters/filters_spec.js

Looks like `''` and `null` are casted into `undefined`, so I chose `false` to be as "no-symbol param". 
What do you think?

Currency symbol

---

src/transition/transition.js
test/unit/specs/transition/transition_spec.js

Fixes #1241
Leave doesn't set up the css callback if there's a js callback, so I did the same for enter.

Don't set up css transition callback if there's a js callback.

---

.eslintrc
package.json
src/watcher.js
test/.eslintrc

eslint's operator-linebreak rule now supports the ternary operator (https://github.com/eslint/eslint/issues/3274).
Changed the rule to match the code, and fixed the single instance
in the code that was different.

fix eslint ternary operator error

---

src/directives/for.js

Cater for scenario where there is no previous sibling of el. Solution to #1249 and similar to #982. Occurs when dragging between lists using a drag and drop library such as RubaXa Sortable.

Return if no previousSibling of el found

---

src/directives/model/select.js
test/unit/specs/directives/model_spec.js

demo: http://jsfiddle.net/evantre/eokkguxx/
if change select's options, it well report error about "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

fix select element can't removeChild optgroup's option

---

src/directives/model/select.js
test/unit/specs/directives/model_spec.js

fix #1299 , when remove optgroup, the children will be undefined.

fix #1299, correct the loop counter

---

src/directives/for.js
test/unit/specs/directives/for/for_spec.js

optionally binding the iteration index (or key when iterating over an
object) to a name to simplify work with nested `v-for`s

allow optional `(key,val) in arr` syntax for `v-for`

---

src/compiler/compile-props.js
test/unit/specs/misc_spec.js

With IE 10 & 11 (haven't tested on Edge yet), we cannot use title as a prop. Using `:title` or `v-bind:title`, IE seems to convert it to a static title attribute, which Vue will pick up instead of the bound attribute. Example:
http://codepen.io/anon/pen/epryMp
In this PR, a bound `title` attribute is preferred over a static title attribute. 
Perhaps all bound attributes should be preferred over static if both are specified on an element?

IE title binding issue

---

src/directives/public/for.js
test/unit/specs/directives/public/for/for_spec.js

Allow the scope created by `v-for` to access its parent scope's $refs and $els.

v-for: support access for parent scope's $refs and $els in for context.

---

package.json
src/compiler/compile-props.js
src/util/env.js
test/unit/specs/misc_spec.js

A follow on from: https://github.com/vuejs/vue/pull/1639
There are more attributes other than `title` which IE has issues with. (`id`, `lang`, `language`,`dir`, etc)
e.g: http://codepen.io/anon/pen/yYxBPy
In this PR, we feature detect binding syntax issues, if the current browser does have this issue, we check every prop for a bound alternative, (`:`, `v-bind:`, `*.sync`, `*.once`) and if present, use the bound prop over a static prop.
`class` is ignored. Buy ignoring it the behavior matches other browsers (bound classes get passed down to component root element)

IE should prefer bound props over static props other than class

---

src/filters/array-filters.js
test/unit/specs/filters/filters_spec.js

The limit filter is too limited by the fact that it's always a 0 offset, this commit allows a second parameter defining the offset allowing for onscreen pagination etc.

Add offset facility to limit filter aka mysql limit

---

src/observer/index.js
test/unit/specs/observer/observer_spec.js

I create the object with `Object.create(null)` for plugin, and when it would try to define as reactivity object with `Vue.util.defineReactive`, occured the `TypeError` in `Observer.create`.
Please see the following jsfiddle:
https://jsfiddle.net/kazupon/yo2cmsLp/1/
In Vue.js, Can I define the reactity object was created with `Object.create(null)` ?
If this is bug, I hope that you will check PR.

Occurred TypeError in Observer.create

---

src/compiler/compile-props.js
src/directives/internal/class.js
src/directives/public/el.js
src/directives/public/for.js
src/instance/state.js
src/observer/index.js
src/util/lang.js
src/util/options.js
test/unit/specs/api/data_spec.js
test/unit/specs/instance/state_spec.js
test/unit/specs/observer/observer_spec.js
test/unit/specs/parsers/path_spec.js
test/unit/specs/util/lang_spec.js

I squashed #1809 into one commit.

fix: ocurred error in 'set' and 'delete' utility functions

---

src/directives/public/for.js
src/instance/misc.js
src/watcher.js
test/unit/specs/directives/public/for/for_spec.js

Continuation of this work: https://github.com/vuejs/vue/pull/1441

Reverse filters support for v1.0

---

src/directives/public/for.js
src/instance/misc.js
src/watcher.js
test/unit/specs/directives/public/for/for_spec.js

Revert "Reverse filters support for v1.0"

---

src/directives/internal/prop.js
src/util/component.js
test/unit/specs/directives/internal/prop_spec.js

Add a force convert option for component. Here is an example:
```html
<script>
export default {
props: {
size: {
type: Number,
coerce: 'number',
default: 48,
}
}
}
</script>
```
And then I can use:
```html
<avatar size="38"></avatar>
```
Otherwise, size will always be String, it won't pass the validation.

add coerce option for component props

---

src/observer/array.js

I found this issue by a [question](http://stackoverflow.com/questions/34388349/vue-js-binding-radio-elements-of-same-name-to-array) on StackOverflow.
If the `index` is string, the `this.length` assigned with the concatenated value of `index` and `1`.

[fix] Convert string to number

---

src/directive.js
src/instance/api/data.js

您好，非常抱歉再来骚扰您。
这个是我上次提的[Issuess](https://github.com/vuejs/vue/issues/2036)，非常感谢您的回答。
晚上发现在1.0x版本中$watch存在一个问题，您的batcher中存在两个队列，一个是用户注册的Wather的队列，一个是内部代码注册的Watcher。在将watcher推入队列的时候，用watcher.user判断应该推入哪个队列。
我想起在0.11版本中vm的$watch方法中，实例化Watcher的时候是设置了user为true的。
而在新的1.0x版本中，为什么$watch代码里初始化Watcher的时候却没有设置user。
下面是两个版本的对比:
``` Javascript
// 摘至1.0x版本的$watch方法：
var watcher = new Watcher(vm, expOrFn, cb, {
deep: options && options.deep,
sync: options && options.sync,
filters: parsed && parsed.filters
})
```
```Javascript
//摘至0.11版本的$watch方法：
watcher = vm._userWatchers[key] =
new Watcher(vm, exp, wrappedCb, {
deep: deep,
user: true
})
```

在$watch方法中初始化Wather的时候，user选项是不是漏写了？

---

src/observer/index.js

https://github.com/vuejs/vue/issues/2008
解决此issue中出现的特殊问题
发现和解决都是@yuhere 做的，我只是帮他提一个PR

object的倒序排列会在一些特殊环境下造成影响(如数据库字段依赖JSON顺序时)

---

src/instance/api/data.js
test/unit/specs/api/events_spec.js

When handle events by inline statement, propagation continuing is not working.
By the way: https://github.com/rhyzx/vue/blob/fix-inline-statement-propagation/test/unit/specs/api/events_spec.js#L186-L187 ,  binding handler using `v-on` directive to component will be treat as its inner handler, this is **non-intuitive** in my opinion, eg:
```js
// parent.vue
<foo @test="stopPropagation"></foo>
```
`test` event dispatched by `foo` will still propagate even if `stopPropagation` returned `false`, what do you think about this? @yyx990803

Fix inline statement propagation

---

src/compiler/compile.js

Eg: `<div v-if>`, i think this is a bug, expression validation should be in directive itself.
ps. Do i need to add test for this?

allow empty expression in terminal directives

---

README.md

It's probably better to have third-party developments be added to the growing list in awesome-vue instead of that outdated wiki page.

Vue-related awesomeness goes to awesome-vue

---

test/unit/specs/misc_spec.js

When assigning property to a frozen object, an error is occurred in my chrome 47.0.2526.106

Fix test about assigning to frozen object in chrome.

---

src/cache.js
test/unit/specs/cache_spec.js

- Fixing cache polution when putting an item with the same key multiple times
- Making shift() to reduce the current size of the cache

Cache fixes

---

src/directives/public/bind.js
test/unit/specs/directives/public/bind_spec.js

See #2169
Final solution:  attribute with boolean value will be treat as boolean attribute.

Boolean attributes

---

src/directives/public/on.js
test/unit/specs/directives/public/on_spec.js

Currently when using the `delete` alias in a on directive with keyup `delete" does not support using backspace. This seems quite counterintuitive. Additionally, on Mac keyboards the key normally identified as "backspace" on PC keyboards is called "delete." I was fairly surprised when using the delete modifier didn't detect the key.
I came upon this when developing a search / tag field that turned a search query into tokens when hitting enter or space. I wanted a way to delete tokens without using the mouse. The solution I came up with was detecting the delete key and removing the last token if the search field was empty. I spent 10 minutes debugging code until I realized that I had to press fn+delete (equivalent of DEL / forward delete on a Mac laptop-sized keyboard) for it to actually …

Support backspace with "delete" keycode alias

---

README.md

As proposed in #2303, I added documentation links to reactive data binding, component, and transition features.

Add doc links to core features

---

src/instance/internal/misc.js

Allow this use case:
```javascript
const component = Vue.extend({
template: '<div><dynamic></dynamic></div>',
data() {
return {
path: 'some/path';
}
},
components: {
dynamic: function(resolve) {
// "this" would be undefined otherwise, preventing us from using the instance's data
require([`${this.path}/dynamic_module`], resolve);
// System.import(`${this.path}/dynamic_module`).then(resolve)
}
}
});
```

Pass a context to factory functions

---

src/compiler/compile.js
test/unit/specs/compiler/compile_spec.js

Repo: https://jsfiddle.net/rhyzx/qdyq4z7z/2/
This is because Vue will [replace](https://github.com/vuejs/vue/blob/dev/src/instance/api/global.js#L157) old options with new one instead of extending exist options when `mixin()`, so compiler will get an outdated reference of [directives definition object](https://github.com/vuejs/vue/blob/dev/src/compiler/compile.js#L630).

Fix custom terminal directive with global mixin

---

src/config.js
src/observer/index.js
test/unit/specs/directives/public/for/for_spec.js
test/unit/specs/observer/observer_spec.js

Test whether a property is configurable before defining it as reactive

---

src/directives/public/on.js

I found this when investigating the possibility of **extending modifiers for `v-on`**.
This is feature is useful in some situation, eg: `real-blur`
```js
Vue.modifier('real', function (handler) {
return function (evt) {
if (evt.type !== 'blur' || document.activeElement !== evt.target) {
return handler.call(this, evt)
}
}
})
```
@yyx990803  :trollface:

fix key modifiers detecting

---

src/compiler/compile.js
src/directives/public/for.js
src/directives/public/if.js
test/unit/specs/compiler/compile_spec.js

There are times when we want to use the `arg` and `modifires` in custom terminal directive, and control the priority.
e.g.
```html
<input type="text" v-validate:feild1.input-off="['required']">
```
Recently, in the following related issues or PR, we became able to define the terminal directive.
- allow empty expression in terminal directives
https://github.com/vuejs/vue/pull/2137
- transfer DOM
https://github.com/vuejs/vue/issues/2130
However, we can not yet.
I fixed this issues.
I hope that this PR are merged with you.
Please check the codes.

Improve terminalable directive

---

src/compiler/compile.js
test/unit/specs/compiler/compile_spec.js

Fix terminal directive compilation loop

---

src/filters/array-filters.js
test/unit/specs/filters/filters_spec.js

This is refers to the feature request #2518
I replaced the deconstructing array with a simple array because it makes it easier to use an array from data or computed properties: `files | orderBy sortKeys` instead of `files | orderBy 'name' 'size'` with `sortKeys = ['name', 'size']`. Tell me your thoughts about it

Multiple field order by

---

src/directives/internal/class.js
test/unit/specs/directives/internal/class_spec.js

Support for mutiple class names as key

---

src/parsers/text.js
test/unit/specs/parsers/text_spec.js

Since `text` is being used as the key in `cache.get(text)` and the
cache is checked *before* newlines were removed, the cache would always
miss if the input `text` had *any* newlines.
I updated `tagRe` to match tags which contain newlines, and added an
extra test case to ensure newlines outside of tags are preserved

[fix] Don't remove newlines during parseText

---

test/e2e/markdown.js
test/e2e/svg.js
test/unit/specs/api/data_spec.js
test/unit/specs/api/lifecycle_spec.js
test/unit/specs/async_component_spec.js
test/unit/specs/compiler/compile_spec.js
test/unit/specs/directives/element/partial_spec.js
test/unit/specs/directives/element/slot_spec.js
test/unit/specs/directives/internal/class_spec.js
test/unit/specs/directives/internal/component_spec.js
test/unit/specs/directives/internal/prop_spec.js
test/unit/specs/directives/public/bind_spec.js
test/unit/specs/directives/public/for/for_spec.js
test/unit/specs/directives/public/if_spec.js
test/unit/specs/directives/public/model_spec.js
test/unit/specs/directives/public/ref_spec.js
test/unit/specs/directives/public/text_spec.js
test/unit/specs/instance/misc_spec.js
test/unit/specs/misc_spec.js
test/unit/specs/parsers/expression_spec.js
test/unit/specs/parsers/template_spec.js
test/unit/specs/parsers/text_spec.js
test/unit/specs/util/component_spec.js
test/unit/specs/util/debug_spec.js
test/unit/specs/util/lang_spec.js
test/unit/specs/util/options_spec.js

As discussed, this commit aims to make some tests a bit more serious by replacing `'hi hi ho ho'` with `'foo bar'` :)

Use more serious strings in tests

---

src/fragment/factory.js
test/unit/specs/misc_spec.js

Proposed fix for https://github.com/vuejs/vue/issues/2657

Fix handling v-if along with v-for on a template tag

---

src/directives/internal/component.js

Hello,
__This bug fixes #2666, a html file reproducing the bug within it's context can be found [here](https://github.com/GuillaumeLeclerc/vue-seo/blob/master/examples/hreflang.html)__ 
Since it's only one line I don't think a test is required but I'll explain why the bug occurs and why the PR fixes this.
As stated [here](https://github.com/vuejs/vue/blob/be7339b38ad5083fd0d0baaa2eb9f508b5f9ce23/src/directives/internal/component.js#L55), the compilation is cached so for all components except the first one the attributes are not removed. Users might want to use the ':is' version. In this case it's not removed from the DOM and visible.
This PR fixes the bug in my codebase.
Thank you !

remove :is attribute even when component is cached (fixes #2666)

---

src/util/env.js

在ios微信新版本中，一旦滑动，拖拽等
MutationObserver 就失效了 
先暂时让微信中用setTimeout 支持

修复ios微信中滑动导致双向绑定失效

---

build/webpack.test.config.js

Changing the relative `exclude` path to absolute to make sure tests can be running OK even if Vue is in `node_modules` of other project.

Using absolute exclude path in `build/webpack.test.config.js` 

---

src/watcher.js
test/unit/specs/watcher_spec.js

Fixing 'Maximum call stack size exceeded' when recursively traverse an object which contains some circular references.

Fix error when recursively traverse an object

---

src/instance/internal/init.js
src/instance/internal/state.js
test/unit/specs/instance/state_spec.js

- Added test for checking prop to data clash
- Added test to ensure data function is only called once per strut
- Removed this._runtimeData uses 'data' for prop to data clash check
Fixes: [ISSUE-2687](https://github.com/vuejs/vue/issues/2687)

Fix data functions being called twice. (fix #2687)

---

src/filters/index.js
test/unit/specs/filters/filters_spec.js

I know @yyx990803 has little intention to extend these core functionality, but IMHO you either support something fully or you don't at all. So…
Currently the "currency" filter only accepts one argument: the currency symbol. The number of decimal places is fixed as 2. This can cause troubles with several currencies out there whose number of decimal places can be 0 (e.g. Japanese Yen or Vietnamese Dong) or 3 (e.g. Jordanian Dinar).
This commit modifies the filter to accept an extra optional argument: decimal places, which defaults to 2. With this, one can write `{{ 1234 | currency '¥' 0 }}` to properly display a Yen value. Backward compatibility is maintained.
(Just realized there's a [StackOverflow question](http://stackoverflow.com/questions/35725935/need-a-flexible-currency-filter-in-vuej …

Add support for decimal places in currency filter

---

src/compiler/compile.js

- Fixes [ISSUE-2707](https://github.com/vuejs/vue/issues/2707)
- Terminal directives where incorrectly revieving modifiers from other inline directives

[HOTFIX] [ISSUE-2707] Fix modifiers being incorrectly passed to terminal directives

---

src/util/options.js
test/unit/specs/util/options_spec.js

This works as expected for the `<template>` and the `<script>`, but not for the `<style>`.
I noticed that all the `styles` are loaded, but with the wrong priority.
Maybe some changes are needed to the `vue-loader` to figure out that, right?

Add an option to extend a component

---

examples/select2/index.html

This typo has no effect on the demo.

Fix x-template typo in select2 example

---

examples/commits/index.html

Skimming through 2.0 to grab a hold, and I think some exposure for the authors in the Commits example might be useful.

Expose the author URL in "Commits" example

---

examples/grid/style.css

Because `-user-select` on its own is not a valid CSS attribute, and because we don't discriminate browsers ;)

CSS fixes for "Grid" example

---

examples/modal/index.html
examples/modal/style.css

I've taken the liberty to:
* Rename `modal.css` into `style.css` following other examples' convention
* Merge the two `<script>` tags into one for leaner code.

Some improvements for "Modal" example

---

src/directives/public/bind.js

Fixes https://github.com/vuejs/vuex/issues/162
textarea works different and we need to set it as before.
Same issue is also present on v2.0. @yyx990803 should I open PR for 2.0 too?

Preserve cursor position when changing input from Vuex.

---

src/platforms/web/util/element.js
test/ssr/ssr.sync.spec.js

Hi, I just tried a simple example of v2.0 SSR with \<img\> tag like below.
```js
renderToString(new Vue(compileTemplate({
data () {
return {
imageUrl: 'https://vuejs.org/images/logo.png'
}
},
template: `<div><img :src="imageUrl"></div>`
}
```
Then I see the following warning as an error.
```
[Vue warn]: Unknown custom element: <img> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```
It looks \<img\> tag is just missing in reserved tags. I added it to the list and the warning disappeared.
Also, I added an \<img\> tag into an existing test just in case.

Suppress a warning 'Unknown custom element' with SSR <img> tag

---

src/platforms/web/runtime/modules/attrs.js
src/platforms/web/server/modules/attrs.js
src/platforms/web/util/attrs.js
src/server/create-streaming-renderer.js
src/server/create-sync-renderer.js
test/ssr/ssr.sync.spec.js
test/unit/features/directives/bind.spec.js

Values of BooleanAttr & EnumeratedAttr are added even when their values are `false`. (The attrs are not added when the value is 'null')
For example, the following ':selected' values currently result in `selected="selected"` for both options.
```js
{
data: {
value: 'bar'
},
template: `
<div>
<select>
<option value="foo" :selected="value === 'foo'">Foo</option>
<option value="bar" :selected="value === 'bar'">Bar</option>
</select>
</div>
`
}
```
Only second option should have selected attribute.
F.Y.I. As a current work around, we can set the prop like `:selected="value === 'foo' ? true : null`.

[Vue 2.0] Fix BooleanAttr & EnumeratedAttr serialization

---

test/unit/modules/compiler/parser.spec.js

add parser tests

---

flow/compiler.js
src/compiler/codegen.js
src/compiler/optimizer.js
src/compiler/parser/index.js
src/entries/web-compiler.js
src/platforms/web/compiler/modules/class.js
src/platforms/web/compiler/modules/index.js
src/platforms/web/compiler/modules/style.js
src/platforms/web/compiler/modules/transition.js
test/unit/modules/compiler/parser.spec.js

Currently they are written and treated as special attributes. This pr made them possible decoupled from web platform implementations.
And each platform will custom more attributes as platform compiler modules in the future.
Updates:
* added `modules?: Array<ModuleOptions>` in `CompilerOptions` type
* added `src/platforms/web/compiler/modules/*`
Changes:
* `parser`
* `processClassBinding(element)`
* `processStyleBinding(element)`
* `processTransition(element)`
* `optimizer`
* `isStaticKey`
* `codegen`
* `genData(el)`

extract style/class/transition as web platform compiler modules

---

src/compiler/compile-props.js
test/unit/specs/directives/internal/prop_spec.js

Reference: https://github.com/vuejs/vue/issues/2926

Warn if coerce is not a function

---

test/unit/features/options/delimiters.spec.js

ref #2872
I think it should be somehow emphasized that if we want delimiters to be changed globally we should define Vue.options.delimiters. Doing so in a constructor of our root instance will not have effect (check out 'delimiters should only affect vm' spec). I guess this is desirable, for most of users rely on default delimiters, and we want to be able to use 3rd party plugins.

Delimiters tests

---

src/compiler/codegen.js
test/unit/modules/compiler/codegen.spec.js

in #2953, I found the runtime error in `watcher`.
I fixed this issue.

Fix render codegen issue

---

src/util/options.js
test/unit/specs/util/options_spec.js

Allow extended Vue constructors as the mixins option

---

src/parsers/template.js
test/unit/specs/parsers/template_spec.js

Reference: https://github.com/vuejs/vue/issues/2993

Fix handling comments when template has no tags

---

src/compiler/compile.js

Make rendering of undefined and null in one-time binding mode as same as reactive binding.

Fixed #2988

---

src/cache.js

if the cache size is equal to cache limit and now we put a new entry with an existed key (not the head key), the result is we removed the head entry and updated an existed entry. the cache size will be limit-1. so we need to move the if-statement inside

do not call shift if the key already exists

---

src/directives/internal/transition.js
test/unit/specs/directives/internal/transition_spec.js

Fix #2972
At first I added this test too since manually updating the directive may differ from real updates but then I realised it must be already tested on binding tests so I removed it.
```javascript
it('removes v-transition on dynamic transition', function (done) {
var el = document.createElement('div')
document.body.appendChild(el)
var vm = new Vue({
el: el,
template: '<div :transition="trans"></div>',
data: {
trans: null
},
replace: true
})
_.nextTick(function () {
expect(vm.$el.className).toBe('v-transition')
vm.trans = 'a'
_.nextTick(function () {
expect(vm.$el.className).toBe('a-transition')
done()
})
})
})
```

Fix missing removal of v-transition class

---

package.json

Instead of using globs to be expanded in the shell, ESLint has support for recursively linting `.js` files inside a directory. Another reason for the change would be that `**` was expanding to all files, including files without `js` extension (like git's `.orig`).
If you still want to use a glob, the correct one would be `/**/*.js` but it's a fairly new feature in Bash so I wouldn't recommend that as an alternative.

fix: glob in npm lint script

---

src/directives/public/model/text.js

Fix #3029
Force setting the value actually resets selectionStart and selectionEnd
No test is added because you cannot simulate the bug by using
input.blur()

Prevent setting unchanged value of input on blur

---

test/unit/specs/parsers/expression_spec.js

Not sure if it's just me misunderstanding how things work, but Vue is apparently treating `null` expression as `undefined`. Here is a failed test case to demonstrate the issue. 
If this is confirmed to be a bug, I can try to work on a fix.

Vue treats `null` expression as `undefined`?

---

src/compiler/compile.js

I'm building a tabs component. It is used like this:
```
<tabs>
<tab title="1">Tab1</tab>
<tab title="2">Tab2</tab>
<tab title="3">Tab3</tab>
<tab title="4">Tab4</tab>
<tab title="5">Tab5</tab>
<tab title="6">Tab6</tab>
<tab title="7">Tab7</tab>
<tab title="8">Tab8</tab>
<tab title="9">Tab9</tab>
<tab title="10">Tab10</tab>
</tabs>
```
[Live demo(Works fine)](https://jsfiddle.net/sgd2sLqf/4/)
It works fine when there are less than 10 ```<tab>s```. But tabs will disorder when I have more than 10 ```<tab>s```.
[Live demo(Bug)](https://jsfiddle.net/sgd2sLqf/5/)
The main reason is that the directive sorting by priority is not stable on Chrome.
I fixed this bug using a sort method(time: O(n), space: O(n)),  It also can be fixed using a stable sort method such as merge sort.

Fix bug: directive sort is not stable on Chrome

---

test/unit/modules/compiler/compiler-options.spec.js

add compile options test

---

src/compiler/compile.js

skip compile before process it's :value when a textarea has v-pre attr
Fixed #3184

textarea with v-pre attr should skip compile

---

src/core/vdom/create-component.js
test/unit/features/options/functional.spec.js

Sometimes, there are times when we pass v-on event handlers to `render` function arguments on functional component.
The below URL is implemented example with v-bind on functional component.
http://jsfiddle.net/kazupon/bjp40byw/6/
In example, we need to define handler in `props`. 
I think that come in useful by v-on event handers passing through.

[2.0][suggestion] pass v-on event handlers on functional component

---

src/compiler/compile.js
src/directives/public/for.js
src/directives/public/if.js
src/util/dom.js
test/unit/specs/directives/public/if_spec.js

fix $refs updating

---

src/platforms/web/util/element.js

fix "[Vue warn]: Unknown custom element: `<body>` - did you register the component correctly? ..."

[2.0] [vuejs:next] add "body" as reservedTag

---

src/parsers/expression.js
test/unit/specs/parsers/expression_spec.js

This fixes #3273 but might introduce other bugs. I'm not sure of it.

Handle back-ticks in expression

---

src/platforms/web/runtime/modules/dom-props.js
test/unit/modules/vdom/modules/props.spec.js

I realized `<input :value="value">` is not working on initialization when `value` is `0`.
And also `undefined` is appeared on input field, they are not happened on v1.0
Reproduction: 
[2.0.0-beta.5] https://jsfiddle.net/srbg2em6/1/
[1.0.26] https://jsfiddle.net/srbg2em6/

[2.0] allow to initialize value attribute to 0

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

Since 2 root nodes with `v-if` and `v-else` are guaranteed to return one vnode, they should be considered safe in the root of a template.

Allow 2 root nodes with v-if and v-else

---

src/platforms/web/runtime/directives/show.js
test/unit/features/directives/show.spec.js

Addresses issue described [here](https://github.com/vuejs/vue/issues/2873#issuecomment-237921731).

made v-show respect display values in style attributes

---

src/compiler/parser/index.js

Currently if you try to render `<script>` tag on the server side you'll get an error, which is not right, because server is not restricted by the rules of the browser. It is useful if server-side component is rendering the `<html>` tag with `<head>` `<body>` and everything else

Allow rendering forbidden tags on the server

---

src/compiler/compile.js

I was in this case:
```html
<component :is='componentName' :foo='foo' ></component>
```
And the component pointed had invalid template, leading to this error:
<pre>
[Vue warn]: Attribute ":foo" is ignored on component <b>&lt;component&gt;</b> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment-Instance
</pre>
Now this error also gives the name of the component that failed:
<pre>
[Vue warn]: Attribute ":foo" is ignored on component <b>&lt;component:myComponent&gt;</b> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment-Instance
</pre>

improve debug message for invalid dynamic component

---

src/core/vdom/create-element.js

All results will be a `VNode` or `void`,  createElement won't return `Array<VNode>`.

createElement won't return Array<VNode>

---

package.json
types/index.d.ts
types/test/options-test.ts
types/test/plugin-test.ts
types/test/vue-test.ts
types/vue.d.ts

Related to https://github.com/vuejs/vue/pull/3509
TS declaration files need much hacks, as comments point out.
`import Vue = require("vue")` is the recommended way to import vue because it does not confuse TS/JS users whether to `import default` or `import * as Vue` and it does remind user the difference of commonjs module and es module.

adapt index.d.ts for end users

---

types/options.d.ts
types/test/options-test.ts
types/vue.d.ts

* add “FunctionalComponentOptions” and “ContextObject”
* fix and update types
#3509 and #3582

Fix definitons

---

types/index.d.ts
types/test/options-test.ts
types/test/plugin-test.ts

This patch allows us to import vue's types easier.
We can just import them like `import { ComponentOptions } from 'vue'`.
This is also useful for some plugin creators to use vue's types on their declarations.

Expose all types via index.d.ts

---

src/core/util/props.js
test/unit/features/options/props.spec.js

Vue 1 support this form of prop declaration:
`props: {
someProp: true
}`
[https://jsfiddle.net/89a15uby/](https://jsfiddle.net/89a15uby/)
Vue 2 throw an error `Right-hand side of 'instanceof' is not an object`
[https://jsfiddle.net/jbovp90x/](https://jsfiddle.net/jbovp90x/)

support short prop declaration as prop: true

---

src/core/instance/state.js

Adding an undefined property to `methods` on vue components leads to a very ambiguous error message: `Uncaught TypeError: Cannot read property 'length' of undefined`
Example:
```js
import stuff from './stuff'
export default {
template: '...',
methods: {
someMethod: stuff.someMetod // typo!!!
}
}
```
It's an easy mistake to make. This checks for undefined properties and warns if it finds one.

Add undefined check for instance methods

---

package.json
test/e2e/todomvc.js

Fix broken todomvc test

---

types/test/augmentation-test.ts
types/test/tsconfig.json

Plugins of Vue.js usually add some static or instance properties/methods to `Vue` and some new options to component options.
I think it is good to provide how to augment their typings for the plugin developers.
I add the test code of such augmentation by this PR and it would be the example for it.

Add type augmentation test 

---

flow/options.js

fix lifecycle method name `init` to `beforeCreate`

fix Flow lifecycle method name [Vue@2.x]

---

src/compiler/compile.js
test/unit/specs/compiler/compile_spec.js

fix #3768 
Object.keys(groupedMap) returns an array whose elements are strings, so it breaks the sort function.

fix directive sort compare

---

types/test/vue-test.ts
types/vue.d.ts

According to the [doc](https://rc.vuejs.org/api/#ref), `$refs` is a dictionary of `Vue` instance or `Element`. This pull request reflect this by a union type. So users can declare html elements in `$refs`. 
A test is also added. User defined components may have better knowledge about `$refs`' data structure. So users can also reify special properties to more specific types.
@ktsn your review is appreciated, thanks.

Update `$refs` type declaration

---

src/core/instance/index.js
test/unit/features/instance/init.spec.js

Hi,
Open to different wording on the error & I wasn't sure where to put these tests so I've put them in a new file for now. 
An alternative to this PR would be something like:
```diff
function Vue (options) {
+  if (!(this instanceof Vue)) {
+    return new Vue(options)
+  }
this._init(options)
}
```
I'm not sure which would be better in the long run but the alternative would be more forgiving.
I could also wrap this in env check so this is left out of the production build, but it's also not a lot of code to leave in.
Let me know what you think.

warn user calling Vue() without new

---

types/index.d.ts
types/options.d.ts
types/test/options-test.ts
types/test/tsconfig.json
types/test/vue-test.ts
types/vue.d.ts

According to 06b4703, `namespace` has been removed, so I updated the types.
Also, I fixed the first argument of `$createElement`.
In addition, add `FunctionalComponentOptions` to `Vue.extend`

Fix $createElement and Vue.extend

---

src/core/instance/render.js
test/unit/features/component/component-slot.spec.js

It may be a better way to move the textnode out of the static render tree

Fix #3824 Allow text nodes on static templates in components

---

build/config.js

The license information in `vue.common.js` is needed for compiling bundles with webpack.
Without the license, an app that does `require('vue')` and is compiled with webpack will not give proper attribution to the grat work done by Vue.

add license information to vue.common.js

---

.github/ISSUE_TEMPLATE.md
README.md
examples/elastic-header/index.html
examples/todomvc/app.js
examples/todomvc/readme.md
test/unit/modules/vdom/modules/dom-props.spec.js

Replaced all http vuejs.org links with https.

Switch to https

---

src/compiler/parser/index.js

The current forAliasRE has the first rule greedy (`(.*)`), which will attempt to match whatever it can. This exposes a bug (#3846), where the regex fails if the template happens to have " in " or " of " in its last group. For instance, with the template `for key in [{body: 'Hey in body'}]`, current regex will capture the last group as `body'}]` instead of `[{body: 'Hey in body'}]`. This commit aims to fix this issue by making the first rule lazy instead.
I don't think this really needs a test, but let me know if it does.

Make forAlias regex lazy (fixes #3846)

---

src/core/util/props.js

the getType func only returns the first prop type, even if the prop type is an array.
Add getTypeList func to get prop types. 
fix #3879

add getTypeList to process mutli-type prop

---

src/core/vdom/patch.js
src/platforms/web/runtime/node-ops.js
test/unit/features/directives/model-select.spec.js

fix the render of  multiple select with static template. The mutliple attribute of select dosen't apply at first, so the mutli selected option dosen't work when patching.  fix #3901

fix multiple select render

---

src/compiler/parser/index.js

replace terminator chars  \u2028 and \u2029 to avoid syntax error. fix #3895

replace special terminators chars

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

Update CONTRIBUTING.md's jdfiddle template, and vue's version inside ISSUE_TEMPLATE.md

---

src/platforms/web/runtime/directives/model.js
test/unit/features/directives/model-select.spec.js

If select binding not changed, then needRest should be set to false, and no **change** event should be emitted. fix #3917

select change event fix

---

.github/CONTRIBUTING.md

(fix #xxxxx) info needs to be included in PR title for release log if a special issue is resolved.

Add guide for PR title 

---

examples/commits/index.html
examples/elastic-header/index.html
examples/firebase/index.html
examples/grid/index.html
examples/markdown/index.html
examples/modal/index.html
examples/move-animations/index.html
examples/select2/index.html
examples/svg/index.html
examples/todomvc/index.html
examples/tree/index.html
package.json
src/compiler/parser/index.js
test/e2e/specs/grid.js

Fixes #3940. This was a bit of a brainless error on my part - I apologize. Something I noticed however, is that none of our tests are currently covering the production build of Vue, thus allowing this error to slip through. To prevent this in the future, I was wondering if we should split the unit tests into two groups:
- Development-specific behavior (e.g. warnings)
- Features that should behave the same in both dev and prod, which will perform a second run with `NODE_ENV` set to `production`
I think that work would be well outside the scope of this PR, but as a stop-gap measure to cover production at least a little, I switched all of the e2e examples to use the production build, then tweaked the grid example so that I could add a regression test. 
My thinking is that production is …

fix root v-else not rendering in prod and switched examples to minified vue for better prod coverage

---

src/platforms/web/runtime/transition-util.js

Vue transitions have a wrong timing when having CSS like the following:
```
.[transition-name]-enter-active, .[transition-name]-leave-active {
transition: opacity 0.8s ease, transform 0.7s ease;
transition-delay: 0.4s;
}
```
Which in turn bubbles errors to the console. This PR fixes the bug.
I have a question though: Is parameter re-assign allowed in Vue? It's not configured in the ESlint setup.

Fix using one delay to control all transitions.

---

build/config.js
src/core/observer/watcher.js
src/server/create-renderer.js
test/ssr/ssr-env.spec.js
test/unit/modules/vdom/modules/class.spec.js

Fixed typos.

---

src/core/vdom/create-component.js
src/platforms/web/runtime/directives/model.js
src/server/render-stream.js

Fix minor typos

---

src/platforms/web/compiler/directives/model.js
src/platforms/web/util/model.js
test/unit/features/directives/model-component.spec.js
test/unit/features/directives/model-radio.spec.js
test/unit/features/directives/model-select.spec.js
test/unit/features/directives/model-text.spec.js

fix #3958 #3979 
As for array type case, v-model="model[idx]" binding uses **model[idx]=** internally, so the value change could not be reactive.
the binding model expression maybe be as follows:
- test
- test[idx]
- test[test1[idx]]
- xxx.test[a[a].test1[idx]]
- test.xxx.a["asa"][test1[idx]]
- test["a"][idx]
So I use a modelParser to parse the model expression to two parts **exp** and **idx**, and if the exp is an Array type, then use $$exp.splice($$idx, 1, value)

v-model binding with array.  (fix #3958,#3979)

---

src/compiler/optimizer.js

Fixed the spelling error of optimizier to optimizer in compiler src.

Typo fix: optimizier -> optimizer

---

src/compiler/parser/index.js
src/platforms/web/compiler/modules/class.js
test/unit/modules/compiler/parser.spec.js

fix problematic use of 'deprecated' in warnings

---

src/platforms/web/runtime/class-util.js

This commit adds a check for falsy names (null or empty string) before attempting to add or remove them, to prevent a DOM exception. A warning will also be triggered if in development env.

Check and warn for falsy class name (fixes #4050)

---

flow/compiler.js
flow/vnode.js
src/compiler/helpers.js
src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-checkbox.spec.js
test/unit/features/directives/model-radio.spec.js
test/unit/features/directives/model-select.spec.js

.number modifier should work with select, radio, checkbox (fix #4018)

---

flow/compiler.js
packages/vue-template-compiler/build.js
src/sfc/parser.js

Add support attribute module

---

src/util/component.js

Due to project requirements and deadlines, we're unable to upgrade to Vue 2.0. I'm backporting this change from v2.0. A `<main>` tag is being flagged as a component and causing this error. 
`[Vue warn]: Unknown custom element: <main> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Add main tag to commonTagRE

---

src/core/global-api/extend.js
test/unit/features/options/name.spec.js

keep consistency in dev and prod env

---

flow/compiler.js
flow/vnode.js
src/platforms/web/compiler/modules/style.js
src/platforms/web/runtime/modules/style.js
src/platforms/web/server/modules/style.js
src/platforms/web/util/style.js
test/ssr/ssr-string.spec.js
test/unit/features/directives/style.spec.js
types/vnode.d.ts

fix #3997
Style priority orders as bellow:
1. binding style > static style.
2. parent style > child style.

enable style merge behavior between parent-child components (fix #3997)

---

src/compiler/codegen/index.js
src/compiler/optimizer.js
test/unit/features/directives/once.spec.js

fix #4182
This PR also fix a bug when v-if works with v-once. The generated code is like *_m(1)*, which is cached by the static tree.  I created a [jsfiddle](https://jsfiddle.net/defcc/2wzdcon5/5/) here

fix v-once inside v-for and v-once with v-if (fix #4182)

---

src/platforms/web/runtime/components/transition-group.js

If `name` isn't specified for a `<transition-group>`, then the class name vue uses for moving items will be `undefined-move` instead of `v-move`.

Fix v-move class when name isn't specified

---

types/options.d.ts
types/test/options-test.ts

We forget about activated/deactivated in keep-alive component :scream:  @ktsn @kaorun343 
Adding two optional fields are compatible to older typing API, so this is not a breaking change.

Add missing lifecycle definition

---

src/compiler/optimizer.js
test/unit/features/directives/once.spec.js
test/unit/modules/compiler/optimizer.spec.js

Fix a bug introduced by the PR #4200 , node.elseBlock should be walked together with node.children. I created a [jsfiddle](https://jsfiddle.net/b8hsvv6x/1/) here. It will break with v-if and v-else as root element.

fix markStaticRoots with v-else 

---

src/compiler/codegen/events.js
test/unit/modules/compiler/codegen.spec.js

add ctrl, shift and alt modifiers for v-on

Modifiers key modifier for directive on of Vue.js 2.0

---

src/core/instance/render.js
src/core/util/env.js
test/unit/features/instance/methods-lifecycle.spec.js
test/unit/modules/util/next-tick.spec.js

This might seem like a very naive implementation, but I _think_ it should work as expected. When we pass a callback to `nextTick`, we just defer it (ideally to the microtask queue), with our preferred strategy being native promises. In cases where promises are polyfilled, it seems projects like Bluebird actually use [very similar scheduling fallbacks](https://github.com/petkaantonov/bluebird/blob/master/src/schedule.js) to `nextTick`, so we should see similar results.

Add promise support to nextTick

---

flow/compiler.js
src/sfc/parser.js
test/unit/modules/sfc/sfc-parser.spec.js

The approach is simple and experimental. Worth discussing
This allow to use other block appart from `template`, `script` or
`style` in the SFC parser. This allows such things as writing tests or
examples directly into the SFC file. Those are meant to be handled by
programs others than vue-loader like vue-play.
an usage example could be:
```vue
<example name="simple">
<my-button some-prop="red">Hello</my-button>
</example>
```
custom playground. The content wouldn't be parsed by the SFC parser. Its third parties' programs responsibility to do so
```vue
<play name="simple">
<template>
<my-button @click.native="increment">Hello</my-button>
</template>
<script>
export default {
data () { return { count: 0 }},
methods: {
increment () { this.count++ }
}
}
</script>
</play>
<play …
```

Support custom blocks in SFC parser

---

types/vnode.d.ts

As `Ctor` is actually a constructor, its type should be `typeof Vue`.

Fix the type of VNodeComponentOptions.Ctor

---

src/core/instance/init.js
test/unit/features/global-api/mixin.spec.js

Fix #4266
This PR fixes the problem that `_scopeId` will be dropped after applying global mixin.
reproduction: https://jsfiddle.net/tutjybnv/
Looks like same problem as vuejs/vue-loader#433

Avoid to drop scope id by applying global mixin

---

src/core/instance/lifecycle.js
src/core/vdom/patch.js
test/unit/modules/vdom/patch/edge-cases.spec.js

Fix #4284 , to recap the bug, in one sentence: 
`vm.$el` should always be the same as `vm.$vnode.elm`
More detail:
1. If a component changes its root element during rendering, all ancestors' placeholder root element's element should be all updated.
2. If one component is the root element of another component, for example `wrapper` in the test case, and wrapper's parent is updated (which triggers wrapper's `updateFromParent`), `wrapper`'s $vnode is not the same as `comp`'s $vnode.parent. While in the initial rendering, these two vnodes are the same one.
To simplify these two statements, we have to keep one invariant: `vm.$el` should always be the same as `vm.$vnode.elm`. Otherwise vdom patching will mistakenly insert new dom node.
If we correctly sync vnode's element when child tree's root …

Ensure Vue instance's vnode and element is up to date

---

src/compiler/optimizer.js

A small change, reuse `no` function from shared/utils.

Reuse no function from utils

---

types/test/options-test.ts
types/test/vue-test.ts
types/vnode.d.ts
types/vue.d.ts

I've added the types that related to the scoped slots and updated `nextTick`'s interface to allow to return Promise.

Update types for new features of v2.1

---

examples/commits/index.html
examples/elastic-header/index.html
examples/firebase/index.html
examples/modal/index.html
examples/select2/index.html
examples/svg/index.html
examples/tree/index.html

NOTE:
consistently keep the examples of vuejs.org.
https://vuejs.org/v2/examples/

improve examples html title

---

src/compiler/helpers.js
src/core/vdom/helpers/update-listeners.js
src/platforms/web/runtime/modules/events.js
test/unit/features/directives/on.spec.js
test/unit/modules/compiler/codegen.spec.js

Modifier once for v-on is added.

Modifier once for v-on

---

flow/component.js
src/compiler/codegen/events.js
src/core/instance/render.js
test/unit/features/directives/on.spec.js
test/unit/modules/compiler/codegen.spec.js

An improvement for #4102 
1.  KeyCodes support array type.
2. Build-in keycodes alias could be overrided on the userland.

Support mutliple keys for keycode

---

src/core/instance/state.js

The reason `data` has to be a function in components seems to be a point of confusion for many, so I've linked to an explanatory example in the warning.

Reference doc in component data function warning

---

build/build.js
build/config.js
src/core/index.js
src/entries/weex-framework.js

Use the rollup replace plugin to replace weexVersion and (Vue) version
inside the files.
I checked the built files and it looked fine but since I don't know how weex works, I'll like a second check @Jinjiang 🙏
edit: ~~I realised this approach doesn't work with the current release workflow~~ nvm, it uses the env variables

Refactor version replacement

---

src/core/config.js
src/core/vdom/create-element.js

> As described in [How to implement the `<div>` component on the web](https://github.com/weexteam/weex-vue-framework/issues/12), this is a way to achieve solution 1.
Add a global configuration function `parsePlatformTagName` to be able to parse the real tag name for the specific platform. It takes a string and return it directly by default.
This function should be used in conjunction with `isReservedTag`.

Add `parsePlatformTagName` config

---

src/core/global-api/extend.js
test/unit/features/options/name.spec.js

This commit adds a more informative warning message for invalid component names. Also fixes a typo.

More informative warning message for comp name (closes #4428)

---

src/compiler/parser/index.js
test/unit/features/directives/bind.spec.js

fix v-bind.prop parse (fix #4432)

---

flow/component.js

This PR attempts to address this [related Issue](https://github.com/vuejs/vue/issues/4410).
Regression tests have been run to make sure it does not break the current functionality.
Thanks!

[#4410] Change any to mixed to make it type-safe

---

src/core/vdom/helpers/normalize-children.js
test/unit/modules/vdom/create-element.spec.js

fix #4466 . Check boolean type

Update normalize children (fix 4466)

---

src/core/instance/render.js
test/unit/features/directives/for.spec.js

Fix #4497 
At first I added an else if at the end since strings are rarely used in v-for loops but it felt wrong not to reuse the first if

Add missing string handler in v-for

---

src/entries/weex-framework.js

Added `weex` instance variable:
* `weex.document`
* `weex.config`
* deprecated `Vue.prototype.$getConfig()`
* `weex.require(name)`
* deprecated `__weex_require_module__(name)`

[weex] supported `weex` instance variable

---

src/core/config.js

Update default value for `ignoredElements` so that the docs (https://vuejs.org/v2/api/#ignoredElements) don't lie.

Set default value for ignoredElements to [].

---

packages/vue-template-compiler/README.md

NOTE:
Everytime, we tried not to change links.

fix type definition links

---

src/platforms/web/runtime/modules/dom-props.js
test/unit/features/directives/bind.spec.js

update dom prop for option.value (fix #4494)

---

src/compiler/parser/index.js

Where I work, it's not uncommon to come across `<script>` tags in templates that would not be trivial to move into separate files. If Vue will prevent the execution of the contents of these tags, I think the warning should say so. As it is, it reads more like a recommendation than a requirement:
`Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>`. 
I don't know if the language I've added is best, but it's an example of text that tells the user they should not expect their code to run. Feel free to edit as desired.

Specify that tags with side-effects will not be parsed.

---

src/shared/util.js
test/unit/features/directives/model-checkbox.spec.js
test/unit/features/directives/model-radio.spec.js
test/unit/features/directives/model-select.spec.js

Update loose equal function, check toString value for primitive type (fix #4514)

---

src/core/util/props.js

Additional info in issue  #4538

Don't cast empty string to Boolean if prop types include String and Boolean (fix #4538)

---

src/core/vdom/patch.js
test/unit/modules/vdom/modules/dom-props.spec.js

fix #4535 
relative commit https://github.com/vuejs/vue/commit/d0afcd3cf9ad572621676ef02005d226cb4ac7c4#diff-4c8bbf2657619e18d911574dbc6b32e9

Node maybe be removed by v-html/v-text (fix #4535)

---

src/entries/weex-framework.js

In Weex, the `Vue` variable in each js bundle is generate by `Vue.extend({})` actually, and pass some global properties to it. But forget to expose the `version` and `config` on subVue.
I additionally exposed three props to subVue:
+ `version`
+ `weexVersion`
+ `config`
Some libs, such as `Vuex`, may relay on the `version` and `config`.

[weex] Expose version and config on subVue

---

src/compiler/codegen/events.js
src/compiler/codegen/index.js
src/compiler/directives/index.js
src/compiler/helpers.js
src/core/util/props.js
src/shared/util.js

This is an experiment striving to fix #4410. The improvement is based on [CLI tool](https://flowtype.org/docs/cli.html#_). The following command is used to inspect source. 
```bash
flow coverage $TARGET.js --json | jq '.expressions .uncovered_locs[] .start .line'
```
Which prints out all the line number of potential unsound `any` type. Only files under `src/compiler/codegen/` are checked.
To my consternation, we have a lot of `implictAny` in code base, (and I have no idea why). Fixing these `any` needs some weird typing and dependency on how flow works (in my conjecture).
While I really appreciate @thejameskyle 's suggestion, I'm afraid maybe our team's capability does not match Flow's type system.
As the title indicates, this pull request is experimental, feel free to close it.

[EXPERIMENTAL] Try to really improve flowtype

---

src/compiler/codegen/index.js
test/unit/modules/compiler/codegen.spec.js

Enforce to loop through children to get the correct normalize type (fix #4564)

---

src/platforms/weex/runtime/node-ops.js

In Weex, the `TEXT_NODE` must be the child of `<text>`.
Added special treatment of `TEXT_NODE` in `removeChild`.

[weex] Fix the text node could not be removed properly

---

src/platforms/weex/runtime/node-ops.js

Fix #4046 . Should check the nodeType of child, not the node itself.

[weex] fix the removeChild logic for text node

---

src/compiler/parser/html-parser.js
src/sfc/parser.js

1. Remove the unnecessary argument of parseEndTag.
2. Store the lowerCasedTag in the stack and use it directly.
3. Remove isSpecialTag logic for simplification.
As for **isSpecialTag** logic, the original implementation checks the tagName and its attribute. If it's a **template** with **lang attribute**, it will skip to parse the content inside the template. I think maybe we could simplify it, because the template element is guaranteed by the SFC parser.
```js
const hasLang = attr => attr.name === 'lang' && attr.value !== 'html'
```
For this line, is it an edge case?  There is no proper test case about it, I am not very sure.
Please let me know if anything I missed.

Small refactor for template parser

---

src/platforms/web/compiler/directives/model.js
src/platforms/web/runtime/modules/dom-props.js
test/unit/features/directives/model-checkbox.spec.js
test/unit/features/directives/model-radio.spec.js

fix #4620 
1. use *click* event instead of *change* event.
2. add test case for #4521

Use 'click' event for checkbox and radio (fix #4620)

---

src/entries/weex-framework.js

After a discussion, we feel the `weex.require` api is ambiguity, use `weex.requireModule` is more reliable.

[weex] Use weex.requireModule instead of weex.require

---

flow/compiler.js
src/compiler/helpers.js
src/compiler/optimizer.js
src/compiler/parser/index.js
test/unit/modules/compiler/optimizer.spec.js

Added an extra staticProps to fix #4658.

Mark node with static props as static

---

src/shared/util.js

1. parseFloat() support only one param, see MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat
2. maybe it's better to use isNaN() to judge the conversion result?

fine-tuning of toNumber function

---

build/karma.sauce.config.js

SauceLabs has sunset all versions of Android prior to 4.4:
https://wiki.saucelabs.com/pages/viewpage.action?pageId=67012495
Let me save you the pain I've endured the past few days, getting my SauceLabs Android 4.2 Selendroid configuration upgraded to Android 4.4 on Appium. *Oh honey child let me save you!* 💋

Updated Android 4 SauceLabs configuration

---

examples/todomvc/readme.md

"Building Larger Apps with Vue.js" is not in the 2.X documentation anymore. 
Alternatives:
- link to the original page: https://v1.vuejs.org/guide/application.html
- link to vue-cli, as the previous page suggests? https://github.com/vuejs/vue-cli

Remove dead link

---

src/core/observer/index.js
test/unit/features/global-api/set-delete.spec.js

Since the `Vue.set` support to insert an item to array, the `Vue.delete` should also support to delete an item from array.
Take the following code as an example:
```js
const vm = new Vue({
template: '<div><span v-for="obj in lists">{{obj.name}}</span></div>',
data: {
lists: [
{ name: 'A' },
{ name: 'B' }
]
}
}).$mount()
Vue.delete(vm.lists, 1)
// vm.lists.length--
```
The `Vue.delete(vm.lists, 1)` just delete the property `1` from the array, but the `vm.lists.length` is still be 2. Evaluating `obj.name` at the second time will caught a TypeError (undefined is not an object).

Be able to delete array item in `Vue.delete`

---

src/compiler/parser/html-parser.js
test/unit/modules/sfc/sfc-parser.spec.js

```vue
<template>
<span><</span>
</template>
```
Vue will run into infinite loop with such component.
It's better to give some warning?

fix(sfc): component contains '<' only

---

src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-text.spec.js

This commit aims to close #4733, for the reason explained there.

Remove warnings about inline value attributes for v-model

---

src/compiler/parser/html-parser.js

Chained `replace`s here may cause problems if the order isn't carefully arranged.Currently we get `"` after decoding `&amp;quot;` while `&quot;` is expected.
For a quick fix, I could move the `replace` which replaces `&amp;`s to the last.However, I prefer one single `replace` so that we don't bother with chaining order.

Avoid double-decoding on attribute value

---

src/platforms/web/runtime/class-util.js
test/unit/features/transition/transition.spec.js

`<transition-group move-class=“ value with leading or trailing whitespace ” />`
reproduced:
http://output.jsbin.com/nijuhow/1

fix `addClass` utlil bug

---

src/platforms/web/runtime/node-ops.js
test/unit/features/directives/model-select.spec.js

Fix #4855
edit: Is multiple supposed to be bindable at all? #4864

Fix multiple attr in select with undefined value

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

We have two different JSFiddle starter links here, none of which is the version on Gitter.im (which appears to be more aligned with Vue's coding standard i.e. no root `<body>` tag, spacings and such). Modifying this issue template to use the Gitter.im version instead.

Standardize the JSFiddle starter link

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

Use an inline script tag with unpkg to explicitly show what we're
including. It allows to easily test regressions by appending @2.x.x at
the end of the of the link.
It also allows to directly check if the repro is using the latest
version
Following #4890

Fix JSFiddle links

---

src/server/create-bundle-renderer.js
src/server/run-in-vm.js

DISCLAIMER: I don't have enough knowledge in nodejs nor V8. I read most cpp/internal js  is by guessing and cramming on cppreference.com :/  I welcome any correction!
This pr tries to alleviate the problem in https://github.com/vuejs/vue/issues/4872. When users include third party library into server bundle, the parsing overhead can be smaller.
If user provided global variable is compared with another global variable in library code, they will never be equal because they are executed in different context.
To fix this generally, we have to run library code and user code in the same context. This means we need to parse a lot of code in one request. 
We can skip parsing by creating a `Script` object, and `runInNewContext` is [effectively a …

use vm.Script to avoid reparse

---

flow/component.js
src/core/instance/lifecycle.js
src/core/instance/state.js
src/core/util/props.js
test/unit/features/instance/properties.spec.js
types/vue.d.ts

I've implemented a `$props` special attribute on components to access its props because I thought the feature proposed in #4571 was great.
For this implementation, I rewritten `proxy` function in src/core/instance/state.js to general purpose one.
Thanks for the wonderful suggestion, @akryum!

add $props

---

types/index.d.ts
types/options.d.ts
types/test/vue-test.ts
types/vue.d.ts

Makes watch handler argument to be typechecked when the expression is set
as a function.

typings: type-checking WatchHandler

---

src/core/util/props.js
test/ssr/ssr-string.spec.js
test/unit/features/options/props.spec.js

If the prototype of a function is also a function, we treat it as `Function` constructor.
This check is context independent, so server side can safely extract vue as an external library. And it is not expensive.
Of course it is not silver bullet. Users can pass a value of which the prototype is set to a function. But naughty users can also rewrite `Function` global, so I think this change is at most as bad as current check.
Other counter examples are welcome!

fix #4872, use context agnostic Function constructor check

---

packages/vue-template-compiler/build.js
src/sfc/parser.js
test/unit/modules/sfc/sfc-parser.spec.js

See #4914 
This PR passes attributes down to `parseComponent` so that build tools layered on top of `vue-template-compiler` can have access to that information without having to parse the src to retrieve it.

Pass attributes to parseComponent (addresses #4914)

---

package.json
types/index.d.ts
types/options.d.ts
types/plugin.d.ts
types/test/augmentation-test.ts
types/test/global-test.ts
types/test/options-test.ts
types/test/plugin-test.ts
types/test/tsconfig.json
types/test/vue-test.ts
types/typings.json
types/vue.d.ts

Hi.
This is a PR to add TypeScript definition files for Vue.js 1.x into this repository.
Since Vue decided to bundle its definition files, they were hosted on DefinitelyTyped.
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13230
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13235
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13236
However, as these PRs imply, `vue.d.ts` was removed and currently there's no way to manage the 1.x's one.
In addition, there were a lot of changes between 2.x's and 1.x's definition, such as `vuejs` namespace, plural or singular. So I changed its content in order to allow users to use what version they like with TypeScript.
Of course, the past definitions were written for TS 1.x, but this one is for TS 2.x.
* …

add types for Vue 1.x

---

flow/component.js
src/core/instance/events.js
test/unit/features/instance/methods-events.spec.js
types/vue.d.ts

support $on multi event - #4856

---

src/core/instance/state.js
test/unit/features/options/props.spec.js

When you specify a method on a component with the same name as a prop you get an error about mutating a prop directly, but it can be hard for people new to vue to figure out what this means.
This PR adds a more explicit warning message indicating exactly what went wrong.

Warn when defining a method with same name as a prop

---

src/core/config.js

I found it, when I'm working flowtype definition of vue into [`flow-typed`](https://github.com/flowtype/flow-typed). (registration soon 😉 ) 
`Vue.config.keyCodes` allow the `Array<number>`.
https://github.com/vuejs/vue/blob/0e2dafa74ccecf57fbbac6f828884558a8fbd794/test/unit/features/directives/on.spec.js#L272
related:
https://vuejs.org/v2/api/#keyCodes

improve Vue.config.keyCode typing

---

src/core/vdom/helpers/normalize-children.js

Fix comment typo in normalize-children.js
Ignoring this typo that also appears in `dist` and `packages`.

Fix comment typo

---

src/core/instance/inject.js
test/unit/features/options/inject.spec.js

Check property exists instead of truthy value

---

.github/PULL_REQUEST_TEMPLATE.md

Adding a Pull Request Template for external contributors.
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring
[X] Other... Please describe:
A template to help people to contribute with Vue
```
```
[ ] Yes
[X] No
```

Pull Request Template to GitHub

---

flow/component.js
src/core/instance/events.js
test/unit/features/instance/methods-events.spec.js
types/vue.d.ts

support $off multi event

---

src/core/util/lang.js

I found unnecessary conditional in lang.js.
https://github.com/vuejs/vue/blob/dev/src/core/util/lang.js#L30-L32
if `bailRE.test(path)` is true, It's return.
So, the next else clause is unnecessary.

Fix unnecessary conditional.

---

flow/component.js
flow/global-api.js
src/core/observer/index.js
test/unit/modules/observer/observer.spec.js

I improved `Vue.set/Vue.delete (vm.$set/vm.$delete)` flowtype interface, and also I refactored these API.
In the API of `Vue.set `(vm.$set)`, docs said:
> Returns: the set value.
https://vuejs.org/v2/api/#Vue-set

improve data set/delete API

---

src/core/instance/lifecycle.js

Make the warning more explicit for template complier.
Plus, el option which will be used to extract the template should also emit the warning.

Add the runtime-only warning for el in-DOM HTML template

---

src/platforms/web/compiler/util.js

In vue 2.0, the template is parsed by a Virtual DOM. The paring process is case-sensitive. For example, the VDOM can distinguish between `<Button>` and `<button>`. However, the function is `isNonParsingTag` is case-insensitive which shouldn't be.

NonParsingTags should not be case-insensitive

---

packages/vue-template-compiler/README.md
src/sfc/parser.js
test/unit/modules/sfc/sfc-parser.spec.js

SFC `parseComponent` pads all content with spaces when `{ pad: true }` is provided. That is, all content is converted to spaces. Previously, each line was truncated to `//`. The new padding method works better with character-oriented tools that calculate positions by distance from the beginning of the file instead of by line
number.
Fixes #5058.

SFC parseComponent pads complete content with spaces

---

test/e2e/specs/todomvc.js
test/ssr/ssr-string.spec.js
test/unit/features/component/component-keep-alive.spec.js
test/unit/features/component/component-slot.spec.js
test/unit/features/directives/bind.spec.js
test/unit/features/global-api/extend.spec.js
test/unit/features/options/el.spec.js
test/unit/features/options/lifecycle.spec.js
test/unit/features/options/props.spec.js
test/unit/features/transition/transition-mode.spec.js
test/unit/modules/compiler/codegen.spec.js
test/unit/modules/compiler/optimizer.spec.js
test/unit/modules/compiler/parser.spec.js
test/unit/modules/sfc/sfc-parser.spec.js
test/unit/modules/vdom/patch/edge-cases.spec.js
test/weex/compiler/style.spec.js
test/weex/runtime/framework.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(test): fix some typos

---

src/core/observer/dep.js
src/platforms/web/runtime/components/transition-group.js
src/platforms/web/runtime/modules/transition.js
src/platforms/web/runtime/transition-util.js
src/platforms/weex/framework.js
src/server/create-bundle-runner.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Note that packages/* and dist/* changed too, but I didn't included in commit.

chore(src): fix some typos

---

src/compiler/codegen/index.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
I am not very sure this is a breaking change or not on type definition.

fix a typo on type definition name

---

src/compiler/parser/html-parser.js
test/unit/modules/compiler/parser.spec.js

fix #5121: parse content in textarea as plaintext

---

test/unit/features/directives/on.spec.js

It seems that the previous way is unable to change the value of input.checked, so input.checked will not equal to true even if when after removing the prevent modifier.

fix v-on unit test

---

src/compiler/codegen/events.js
test/unit/features/directives/on.spec.js
test/unit/modules/compiler/codegen.spec.js

fix wrong order of generate modifier code

---

src/core/vdom/create-component.js
test/unit/features/component/component.spec.js

Hi,
Please see #5145 
This patch adds a warning when user is not passing props in kebab-case mistakenly, for example:
```html
<foo someProp="bar"></foo>
should be
<foo some-prop="bar"></foo>
```
I know this is stated on the guide, but since it's a very common mistake (based on the questions on stackoverflow (see the issue above) [and the](https://forum.vuejs.org/t/unable-to-pass-data-from-parent-to-child-component/1763/1) [forum](https://forum.vuejs.org/t/need-help-with-passing-a-boolean-prop-to-a-comonent/3996/1 )), I think it is worth to add a warning and I believe this will save a lot of people's debugging time and provide a more friendly development …

Warn when not passing props in kebab-case

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

warn when template contains text outside root element

---

flow/compiler.js
src/compiler/parser/html-parser.js
src/compiler/parser/index.js
src/entries/web-server-renderer.js
src/platforms/web/compiler/index.js
src/platforms/weex/compiler/index.js
src/platforms/weex/util/index.js
test/weex/compiler/compile.spec.js

Fix https://github.com/weexteam/weex-vue-loader/issues/8 .
And add more reserved tags.

[weex] Support unary and left open tags

---

src/server/render.js
test/ssr/ssr-string.spec.js

SSR `v-show` directive should be merged from parent to child component.
It could be reproduced via this [github repo](https://github.com/defcc/v-show-ssr-bug/). 
And the demo code is bellow:
```js
var Vue = require('vue/dist/vue.common.js')
var createRenderer = require('vue-server-renderer').createRenderer
var renderToString = createRenderer().renderToString
const vm = new Vue({
template: `
<foo v-show="false"></foo>
`,
components: {
foo: {
render: h => h('bar'), …
```

fix SSR v-show render.

---

src/core/instance/inject.js
test/unit/features/options/inject.spec.js

fix provide isn't reactive with a single array

---

src/core/instance/inject.js
test/unit/features/options/inject.spec.js

fix(inject): change warn message when trying to mutate an injected value

---

src/platforms/web/runtime/directives/model.js

On IE9, we are currently marking `vmodel` flag in real DOM and virtually trigger `input` event when `selectionchange` is triggered by the element. But `input[type=password]` element is not set `vmodel` flag since it does not match the condition.
BTW, should we also add conditions for other input types that can be input texts like `search`, `url` and so on?

handle v-model on password input field on ie9 (fix #5250)

---

src/core/observer/index.js
test/unit/modules/observer/observer.spec.js

Since arrays can be treated as normal objects in JavaScript and contain a mix of numeric and named properties, this patch makes `Vue.set` and `Vue.del` deal correctly with named properties on reactive arrays.

Allow named properties on reactive arrays.

---

src/core/instance/state.js
test/unit/features/options/computed.spec.js

I ran all test locally. I'm having some failures related to SSR and selenium which appear to be completely unrelated. I've confirmed the new test works by reverting my change and adding it back in.
I am using `noop` for the getter if one does not exist to avoid exceptions when calling functions on the getter.

Warn and handle missing get in computed (fix #5265)

---

src/core/vdom/patch.js
test/unit/features/component/component.spec.js

This PR fixes https://github.com/vuejs/vue/issues/5321
Reproduction link: https://jsfiddle.net/rstoenescu/uqsath1t/2/ (follow instructions in the Github issue)

fix #5321 don't throw error when node gets relocated

---

src/core/vdom/modules/directives.js
test/unit/features/error-handling.spec.js

handle errors thrown by directive hooks (#5314)

---

src/core/util/options.js
test/unit/features/global-api/mixin.spec.js

This PR moves a constructor check in `mergeOptions` to the head of the function so that we can use a extended Vue constructor not only as `mixins`/`extends` options but also as global mixin. This fixes vuejs/vue-class-component#83

allow an extended constructor as global mixin (fix vue-class-component#83)

---

src/platforms/web/runtime/modules/style.js
src/platforms/web/server/modules/style.js
test/ssr/ssr-string.spec.js
test/unit/features/directives/style.spec.js

When exploring [css-in-js solutions](https://github.com/MicheleBertoli/css-in-js) for vue, I came across the fact that some auto prefixed style objects (for example, by [postcss-js](https://github.com/postcss/postcss-js)) cannot be directly used as `style` option on elements, when they have an array as value, e.g.
```
{ display: ['-webkit-box', '-webkit-flex', '-ms-flexbox', 'flex'] }
```
...which happens when a rule value needs to be prefixed, other examples:
``` …
```

Support auto-prefixed style value as array (client/ssr)

---

src/server/webpack-plugin/util.js
types/vue.d.ts

Vue 2.2.0 added support for Vue.delete(arr, index). This updates the TypeScript definition to allow that.
Refs: https://github.com/vuejs/vue/releases/tag/v2.2.0

Support Vue.delete(arr, index) in TypeScript definitions

---

src/core/instance/render-helpers/resolve-slots.js
test/unit/features/component/component-slot.spec.js

Allow slot names to be numbers

---

src/core/instance/init.js
test/unit/features/global-api/mixin.spec.js

- [] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
This patch fixes vuejs/vue-class-component#87 issue.
This includes following changes:
* Fixing the problem that Mixing feature drops original lifecycle hooks.
* Its test code.
In my environment, some e2e tests failed. But these tests also fail without my modifications.

fix mixin issue(fix vuejs/vue-class-component#87)

---

package.json
packages/vue-server-renderer/package.json
src/server/webpack-plugin/client.js

Hello. During upgrade process of Nuxt.js to vue 2.3.x (nuxt/nuxt.js#633) we encounter strange behavior which adds duplicate entries to `initial` section of client manifest json file. This PR fixes this issue and also ensures every section's items are unique to prevent such kind of problem in future. This PR also prevents an unexpected exception when detecting and ignoring duplicated chunks.
```js
{
"publicPath": "/_nuxt/",
"all": [
"0.nuxt.bundle.309097aded56ffb03943.js",
"1.nuxt.bundle.38d034e2ba6054b908d2.js",
"nuxt.bundle.83400ec2bd4f29e215ba.js",
"vendor.bundle.5953dc67058e339c4b85.js",
"manifest.5953dc67058e339c4b85.js",
"index.html"
],
"initial": [
"manifest.5953dc67058e339c4b85.js",
"vendor.bundle.5953dc67058e339c4b85.js",
"nuxt.bundle.83400ec2bd4f29e215ba.js", …
```

[vue-server-renderer] ensure assets are unique

---

flow/component.js
flow/global-api.js
src/core/observer/watcher.js
src/core/util/debug.js
src/core/util/env.js
src/core/util/error.js
src/core/util/index.js
src/core/vdom/create-functional-component.js
src/shared/util.js

improve flow type coverage to make `isDef` narrow nullable value to no-null value.
Currently `isDef` cannot narrow nullable value, as tracked in https://github.com/facebook/flow/issues/34. Howerver, we can use a special `%checks` comment to instruct flow inline the function. 
To make this happen, we need first to type check `utl/index.js`. So some type definition changes are required. I have tried my best to keep changes constrained to type level. But still some changes influence runtime.

fix #5539: improve `isDef` type definition

---

src/core/vdom/create-element.js
test/unit/features/options/functional.spec.js

issue: https://github.com/vuejs/vue/issues/5536
Originally I wanted to use `isDef` but the flow was a bit of a problem

Fix when functional component render method retrun null (fix #5536)

---

src/server/template-renderer/parse-template.js
test/ssr/ssr-template.spec.js

fix #5591: keep ssr template interpolation whitespace-insensitive

---

src/platforms/web/runtime/directives/model.js
test/unit/features/directives/model-text.spec.js

Prevent unecessary input trigger with v-model

---

src/core/global-api/mixin.js
src/core/global-api/use.js

```javascript
import Vue from 'vue'
Vue
.use(...)
.use(...)
.use(...)
.mixin(...)
.mixin(...)
.mixin(...)
```

Fix use mixin  API feat continuous operation

---

src/core/vdom/vnode.js

when call `cloneVNode`, the key `isComment` was lost. this could effect `patch` and component was re-created. see this [demo](https://jsfiddle.net/16hf328c/)

clone `isComment` when cloneVNode

---

src/core/instance/state.js
test/helpers/test-object-option.js
test/unit/features/options/computed.spec.js
test/unit/features/options/methods.spec.js
test/unit/features/options/watch.spec.js

https://github.com/vuejs/vue/issues/5605

Warn when component option should be an object, but is not (#5605)

---

src/platforms/web/util/element.js

This change will make sure the below error is not seen while unit testing components using <picture> in their template: [Vue warn]: Unknown custom element: <picture> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Add picture to the isHTMLTag map so it suppresses unneeded warnings while unit testing

---

src/core/vdom/patch.js

improve: the readability of `updateChildren`

---

src/server/template-renderer/index.js
test/ssr/ssr-template.spec.js

Actually, `vue-server-renderer` does not generate valid HTML because of the `as` attribute on `rel="prefetch"`, this PR fix this issue.

fix: prefetch should not have `as` attribute

---

README.md

This PR moves the link to the documentation site under it's own heading in the repo's README.
The reason I submitted this PR is that I often have trouble finding the Vue docs.
When googling I click the Vue github repo link by default. 
When landing on the github repo I am confused as to where the docs are.
Currently there **is** a link to the documentation site, however it is not very noticeable.
In order to make it **more** noticeable and easier for other …

Move link to docs under it's own heading

---

src/compiler/compile-props.js

- [x ] Code style update
- [x ] No
Simply fixed the misspelling for `coercions`

misspelling

---

src/core/instance/events.js
test/unit/features/error-handling.spec.js

Currently handleError is used to handle errors during lifecycle hooks and component rendering. This handles most errors thrown by the component however event handlers are not handled. So a component like:
```
<template>
<button @click="error()">I Throw Errors</button>
</template>
<script>
{
methods: {
error() { throw new Error('thrown!'); }
}
}
</script>
```
Will simple throw an error and the error will never be passed to `handleError` nor is one able to use `Vue.config.errorHandler` for error reporting. For my specific use case I wanted to make sure that the plugin I use to report errors to Honeybadger would catch and report errors in event handlers, but more generally any error reporting that relies on `errorHandler` will require this.
It makes sense to me that, for consistency, Vue …

Add handleError during event handling

---

src/platforms/web/util/element.js

improve: add missing html and svg tag

---

src/core/vdom/create-element.js
test/unit/modules/vdom/create-element.spec.js

warn against non-primitive key

---

src/core/util/options.js
test/unit/features/options/extends.spec.js
test/unit/features/options/watch.spec.js

When performing multiple extends/mixins watches are converted to arrays of handlers.
If the parent does not watch an element, but the children do, it will not run the parent.concat code and instead always wrap the child.
If the child is already an array it does not need to be wrapped again.
Fixing #5652

Added check in merge strat for watches if child is already an array (fix #5652)

---

src/platforms/web/util/compat.js

This change is compatible with text/html and application/xhtml+xml documents.

Fix XHTML incompatibility (fix #5852)

---

src/core/config.js
src/core/util/debug.js
test/unit/features/debug.spec.js
types/test/vue-test.ts
types/vue.d.ts

Similar to errorHandler, but for warnings. https://vuejs.org/v2/api/#errorHandler
Sorry for not following the "Ideally you should open a suggestion issue first and have it greenlighted before working on it." rule, no loss on my side if you don't want to accept this.
I would like this feature as it will allow Vue to call a user provided callback for `warn`ings which helps for asserting the state of warnings during testing or development, without having to either spyon or monkeypatch the `console.error` function.
If adding a **new feature**, the …

Add warnHandler to allow users to set a custom warn callback

---

src/core/vdom/create-component.js
test/unit/features/component/component-slot.spec.js

fix slot resolved incorrect with abstract component (fixed #5888)

---

src/core/observer/watcher.js
test/unit/features/options/computed.spec.js

watcher.get should always clean up observee stack in order to prevent memory leak. Also, non-user
defined watch should rethrow error.
#5975

fix: ensure cleanup in watcher.get

---

README.md

This PR is an update to the README file to include the Vue Land chat hosted by Discord. 😄  Although @egoist has mentioned the chat on Twitter I thought it'd be a good idea to include it in the README so new and old Vue developers know about the resource. Also, I added badges for both the Discord and Gitter chats.
_Since this PR made no changes to Vue's codebase I neglected to run any test._

README update to include Vue Land as questions resource and chat badges

---

flow/component.js
src/compiler/directives/bind.js
src/core/instance/render-helpers/bind-object-props.js
test/unit/features/directives/bind.spec.js
test/unit/modules/compiler/codegen.spec.js

add sync modifier with bind object

---

src/core/observer/array.js

remove unnecessary codes

---

.gitignore
build/release.sh

ignore dist files until release
improves contributor experience
ensures dist files can't be accidentally committed in

chore(git): ignore dist files until release

---

src/platforms/web/runtime/modules/transition.js
src/platforms/web/runtime/transition-util.js

Related to [#5800](https://github.com/vuejs/vue/issues/5800)

Check enterToClass/leaveToClass existence before adding it

---

src/core/observer/index.js
src/shared/util.js
test/unit/features/global-api/set-delete.spec.js

To complement PR #5889 that fixed issue #5884 .

improve Vue.set/Vue.delete API to support multi type of array index

---

src/platforms/web/runtime/class-util.js
src/platforms/web/runtime/components/transition-group.js
test/unit/features/transition/transition-group.spec.js
test/unit/features/transition/transition.spec.js

fix: transition group should work with dynamic name (#6006)

---

.flowconfig
src/core/vdom/modules/ref.js
test/unit/features/ref.spec.js

fix #5997 .
When registering `ref`, if `refs[key]` is an array and `ref` is already in `refs[key]`, then do nothing.

fix #5997: refactor function registerRef

---

src/core/util/options.js
test/unit/features/options/inject.spec.js

Fix #6008, Add merge strategy for provide option

---

src/platforms/weex/entry-framework.js
test/weex/runtime/framework.spec.js

`weex.supports` is used to detect whether a feature is supported in the current environment.
```js
weex.supports(condition: String): Boolean | Null
```
+ a formatted string: `@{type}/{name}`.
The `type` must be "component" or "module", the `name` can be tag name, module name or the method name in a specific module.
+ if supported, returns `true`.
+ if unsupported, returns `false`.
+ if unclear, returns `null`.
```js
// Detects whether the specific component is supported
weex.supports('@component/slider') // true
weex.supports('@component/my-tab') // false
// Detects whether the specific module is supported
weex.supports('@module/stream')  // true …
```

feat(weex): implement "weex.supports" api to support feature detection

---

src/compiler/parser/html-parser.js
test/unit/modules/compiler/parser.spec.js

fix: the first LF following pre and textarea tag should be ignored, fix #5992

---

package.json

Breaking change is only for users, who uses undocumented requires/imports from `vue/src`. After this PR all scripts from `src` folder are not included in npm-package
`src` directory is not used by node package. Removing this directory reduces size of `.tgz` package by 112kb and saves 840kb in each node project, where vue.js is installed

perf: remove src directory from npm module

---

src/shared/util.js
test/unit/modules/vdom/create-element.spec.js

feat(warnings): Suggest casting boolean keys

---

src/core/instance/inject.js
src/core/util/options.js
test/unit/features/options/inject.spec.js

fix #6093 .
See [https://github.com/vuejs/vue/pull/6098#issuecomment-315296414](https://github.com/vuejs/vue/pull/6098#issuecomment-315296414)

fix merge strategy function of option props, methods, inject & computed

---

src/compiler/parser/index.js
test/unit/features/component/component.spec.js
test/unit/modules/compiler/parser.spec.js

fix #6154: use prop when prop modifier was explicitly declared

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/platforms/weex/entry-framework.js
test/weex/runtime/framework.spec.js

**This PR only affects the Weex platform.**
+ [x] Remove `__weex_require_module__` api, use `weex.requireModule` instead. The tast case also has been changed.
+ [x] Wrap IFFE and mock the `global` variable for js bundle. (https://github.com/alibaba/weex/pull/1626)
+ [x] return the instance in `createInstance`.

[weex] Remove legacy api and wrap IFFE for appCode

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/platforms/web/runtime/directives/model.js

[https://github.com/vuejs/vue/issues/6209#issuecomment-317715265](https://github.com/vuejs/vue/issues/6209#issuecomment-317715265)

fix #6209, selected option not updated properly under IE11

---

src/platforms/web/runtime/directives/model.js
test/unit/features/directives/model-select.spec.js

[https://github.com/vuejs/vue/issues/6193](https://github.com/vuejs/vue/issues/6193)
---
It seems we still need the value matching check, only detect options change is not enough.

fix #6193, change event should not be triggered if each value still matches an option

---

flow/component.js
src/core/instance/lifecycle.js
src/core/instance/render.js
test/unit/features/instance/properties.spec.js
types/vue.d.ts

fix #6263: $attrs is undefined when component has no props bug (#6263)

---

src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-checkbox.spec.js

fix($compiler): Allow using array value with array v-model in checkboxes, fix #6219

---

.github/CONTRIBUTING.md

docs(CONTRIBUTING): Fixed a small typo in CONTRIBUTING.md

---

src/core/vdom/create-element.js
test/unit/modules/vdom/create-element.spec.js

fix #6506: render SVGAElement inside a component correctly

---

test/unit/features/component/component-slot.spec.js
types/options.d.ts
types/test/es-module.ts
types/test/options-test.ts

add EsModuleComponent definition

---

build/release-weex.sh
packages/vue-server-renderer/client-plugin.d.ts
packages/vue-server-renderer/package.json
packages/vue-server-renderer/server-plugin.d.ts
packages/vue-server-renderer/types/plugin.d.ts
packages/vue-server-renderer/types/test.ts
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json

As webpack officially supports a config file written in TypeScript, I think it would make sense to have declaration files of webpack plugins.
https://webpack.js.org/configuration/configuration-languages/#typescript
fix #6301

feat(vue-server-renderer): add TypeScript declarations of webpack plugins (fix #6301)

---

src/core/util/options.js
test/unit/features/options/inject.spec.js

fix(provide): provide should default to parentVal during merging, fix #6436

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/core/util/env.js
src/core/util/props.js
test/unit/features/options/props.spec.js

close #6447: fix type checking for primitive wrapper objects

---

README.md

**Summary**
Now the clickable `contributor` part in __README__ will go to 404:

chore: correct the contributor link that goes 404

---

benchmarks/dbmon/lib/memory-stats.js

Signed-off-by: Clark Du <clark.duxin@gmail.com>
1. `perf` will never be `null` or `undefined` due to previous definition, so remove the block
2. even if `perf` is `null` or `undefined`, the block will throw and `Cannot read property` error

refactor: remove always falsy condition on perf

---

src/compiler/codegen/index.js

When I read `genOnce` in `vue-server-renderer/basic.js`, I found that `key` will never be false [here](https://github.com/clarkdo/vue/blob/dev/packages/vue-server-renderer/basic.js#L4329).

refactor: remove ternary operator because key is always true

---

types/options.d.ts
types/test/options-test.ts
types/test/tsconfig.json

Looks like current functional component can have `inject` option but the typings do not have it. https://vuejs.org/v2/guide/render-function.html#Functional-Components

fix: add `inject` option in functional component options type

---

package.json

Setting a default file for jsDelivr

Set jsDelivr default file

---

.circleci/config.yml
build/ci.sh
circle.yml

We are going to migrate to CircleCI 2.0 with #6041, but with a simpler description, we can make the build run time shorter.
When caching node_modules, the build is now finished in 1 minute 20 seconds.
https://circleci.com/workflow-run/7ea0d4e0-48ca-449d-9a52-9880dbbd93a5
In the case of 2.0, we have to describe all of the procedures procedurally, but on the contrary, I think that approach is easy to understand.
Please check this PR 😃 @yyx990803 @posva

Improve #6041, Migrate to CircleCI 2.0

---

.github/CONTRIBUTING.md

Now the clickable contributor link in `.github/CONTRIBUTING.md` is not correct that will go to `404`.
- It's caused by the auto-completed wrong link: https://github.com/vuejs/vue/blob/dev/.github/graphs/contributors
- And the correct link is https://github.com/vuejs/vue/graphs/contributors

chore: correct the contributor link in CONTRIBUTING.md

---

benchmarks/ssr/README.md
packages/vue-template-compiler/README.md

When mentioning certain library names like `vueify` and `vue-loader`, the documentation uses backticks in some places but not in others.  Of the cases I noticed, most were in links.  GitHub permits backticks within links and they are rendered with the fixed-width fontQ
The main README.md omits them for vue-loader.  To show the difference, I took the specific line from the table and included both forms:
| Project | Status | Description |
|---------|--------|-------------|
| [vue-loader]          | [![vue-loader-status]][vue-loader-package] | Single File Component (`*.vue` file) loader for webpack |
| …

doc: spelling and formatting

---

flow/compiler.js
src/compiler/codegen/index.js
src/compiler/helpers.js
src/compiler/parser/index.js
src/core/vdom/helpers/update-listeners.js
src/platforms/weex/compiler/modules/recycle-list/index.js
src/platforms/weex/compiler/modules/recycle-list/text.js
src/platforms/weex/compiler/modules/recycle-list/v-bind.js
src/platforms/weex/compiler/modules/recycle-list/v-for.js
src/platforms/weex/compiler/modules/recycle-list/v-if.js
src/platforms/weex/entry-framework.js
src/platforms/weex/runtime/modules/events.js

+ [x] `v-bind` & `:`
+ [x] `v-if`
+ [x] `v-else`
+ [x] `v-else-if`
+ [x] `v-for`
+ [ ] `v-on` & `@`

WIP: implement Weex native directive compiler for <recycle-list>

---

src/shared/util.js

Attempting to parseFloat on a Symbol throws the error `Cannot convert a Symbol value to a string`. Type checking for a Symbol before attempting to parse avoids the error and allows `Vue.set` to be called on [Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol).

Allow an object's Symbols to be observed

---

src/core/instance/init.js
src/core/instance/lifecycle.js
src/platforms/web/entry-runtime-with-compiler.js

Vue core is marked with performance.measure too vague. (e.g. `<Root> render`)
I think it's difficult to understand intuitively in devtools performance timeline.
the following devtools performance timeline capturing image:
And also vue performance measurement with headless browser API (e.g. puppeteer) is hard to parse from profile data.
the following profile data capturing image:
I hope improvement.

Improve DevTools perfromance user timing measurement name

---

src/core/instance/proxy.js

Improved error message.
Fixes #6657

Improve error msg for non-reactive properties

---

src/core/vdom/patch.js
test/unit/features/ref.spec.js

fix(ref): preserve ref on components after removing root element (#6632, #6641)

---

src/core/util/env.js

I've found it easier to debug my application if I use:
Vue.config.errorHandler = function(err, vm, info) {throw err};
Unfortunately, I found that my error handler wasn't being called if the error was encountered as a result of updating a reactive element.  Tracing back, I found that this was due to nextTick calling console.error directly instead of handleError.  I made this change locally and found that it fixed my problem, and didn't cause any failures with 'npm …

fix: pass errors encountered within nextTick to Vue.config.errorHandler

---

src/core/instance/inject.js
src/core/util/options.js
test/unit/features/options/inject.spec.js

Allow to define inject as object with name and default properties. The default is used if no provide
is found, and no warning is emitted.
close #6097
In case of components that can work both as standalone and as children, it would be nice to be able to provide default values for the not provided dependencies.
It would also avoid the warning for missing inject in case this is one of the expected use case.
inject: Array | { [key: string]: string | Symbol | { name?: …

close #6097: Allow defining optional inject dependency with default values

---

types/vue.d.ts

Modification of Vue's static `config` property type definition.
[Per the documentation of the Vue config's `keyCodes` object](https://vuejs.org/v2/api/#keyCodes), the value of a `keyCodes` property may be either a number or an array of numbers. The current `keyCodes` type definition only accepts a single, non-array number. This PR corrects the type definition to reflect both types of acceptable values.

Extend config keyCodes property type to accept an array of numbers

---

src/server/template-renderer/index.js

Enable intial state script to automatically remove itself from the DOM if server environment is
prod. (https://github.com/vuejs/vue/issues/6761)

feat(ssr): auto-remove initial state script if prod [#6761]

---

src/core/vdom/patch.js

Did not make an issue for this, but would be nice to have this implemented.
To avoid warnings when integrating web components within Vue (e.g. polymer, ionic 4 / stenciljs), we currently need to add them to [ignoredElements](https://vuejs.org/v2/api/#ignoredElements).
I think it would be a nice addition if we would be able to use a wildcard there, for example:
`Vue.config.ignoredElements = ['ion*']`
instead of 
`Vue.config.ignoredElements = ['ion-app', 'ion-header', 'ion-page', 'ion-toolbar', etc....]`
All tests pass: 
```
86 specs, 0 failures
Finished in 0.698 seconds
```
If there are better ways to implement this functionality (e.g. regex), let me know.
If yes, …

feat: ignored elements wildcard

---

src/platforms/web/compiler/modules/model.js
test/unit/features/directives/model-dynamic.spec.js

fix(model): allow arbitrary naems for type binding

---

src/platforms/web/runtime/components/transition-group.js

fix(transition-group): work around rollup tree shaking, fix #6792

---

types/vue.d.ts

TS2.6 introduces strict function variance. `$options`'s type breaks variance check. Relaxing the signature solves this. (We need TS2.6RC to break existing code, this fix is tested locally)

fix(typing): relax $options type for TS2.6+

---

src/core/instance/render-helpers/render-static.js
test/unit/features/directives/once.spec.js

fix(core): static trees should be cached on options (#6826)

---

build/install-hooks.js
build/setup.js
package.json

Currently when running `npm test`, an error occurs: 
```
packages/vue-server-renderer/types/index.d.ts(1,44): error TS2307: Cannot find module 'vue'.
```
It's because that `vue-server-renderer` dependencies are missing, simply run `npm install` under `packages/vue-server-renderer` could solve that.
This PR is trying to improve setup script so that new contributor can run `npm test` successfully.

build: install dependency for vue-server-renderer in setup script

---

.circleci/config.yml
build/setup.js
dist/vue.runtime.common.js
types/test/tsconfig.json

build: map vue to local types, simplify build setup

---

src/core/components/keep-alive.js

Here's my problem in some cases : 
my routes list:  redIndex yellowIndex blueIndex   indexBottom  page1 page2 page3...
just want to cache all the index page except indexBottom page , but include  & exclude can not work together .
i change the match order , so i can write component like this 
<keepalive include ='/index/ ' exclude='indexBottom >...</keep-alive>
i think it would be more convenient in most scnario

fix(keep-alive): higher priority for exclude than include

---

src/core/util/options.js

tweak: The value of this is always undefined

---

src/core/instance/events.js
src/platforms/web/runtime/modules/events.js
src/platforms/weex/runtime/modules/events.js

The development environment on Windows is flaky and crashes a lot. I'm also seeing intermittent failures that seem unrelated to my change (they also occur on the `dev` branch with no changes). Filing the PR now to get feedback and to see if CI has the same failures.

fix #6931: Clean up target variables to avoid memory leaks

---

src/platforms/weex/runtime/components/richtext.js
test/weex/runtime/components/richtext.spec.js

The native render engine of Weex supports the `px` unit, and recommend writing CSS units.
+ Remove the `trimCSSUnit` method.
+ Modify the test cases to support CSS units.
+ Add flow type annotations.

fix(weex): stop trim css units in richtext component

---

package.json
test/weex/cases/cases.spec.js
test/weex/cases/event/click.after.vdom.js
test/weex/cases/event/click.before.vdom.js
test/weex/cases/event/click.vue
test/weex/cases/render/sample.vdom.js
test/weex/cases/render/sample.vue
test/weex/helpers/index.js

Compile the `*.vue` file into js code, then run it in Weex context and compare the render result with the expected virtual dom tree.
It’s black-box testing for `weex-template-compiler`, `weex-vue-framework`, `weex-styler` and `weex-js-runtime`. The source code of the first two packages is in the current repo.
The test files are put in the `test/weex/cases`:
+ `render/`:  One-off render test cases.
+ `[name].vue`: Source code.
+ `[name].vdom.js`: Expected virtual dom tree.
+ `event/`:  Test cases which contain event bindings.
+ `[name].vue`: Source code.
+ …

test(weex): support to test the virtual dom generated form *.vue file

---

src/core/instance/events.js
test/unit/features/instance/methods-events.spec.js

The existing test were passing due to the fact that the $off had a second argument. I have fixed the bug and introduced one more test to test the scenario where it doesn't make use of the second argument.

fix #6945: properly $off array of events

---

README.md

Hi Evan, it seems our logo/website ids were changed from 1 to 5 in [open collective](https://opencollective.com/vuejs) and it's not appearing anymore in the sponsors. I've checked open collective to be sure the payment was sent and we still appear in the Gold sponsors. Can you please check this?
Sorry if it shouldn't be a PR but didn't know where to suggest this change :-(
Best,
Alex

[README.me update] Creative Tim missing from the sponsors list

---

src/platforms/web/runtime/directives/model.js
test/unit/features/directives/model-select.spec.js

https://github.com/vuejs/vue/issues/6903

fix(model): correctly set activeindex of select element in a new v-model

---

types/index.d.ts

fix(types): expose VueConstructor (fix #6999)

---

flow/compiler.js
src/compiler/codegen/events.js
src/platforms/weex/compiler/index.js
src/platforms/weex/compiler/modules/recycle-list/index.js
src/platforms/weex/compiler/modules/recycle-list/text.js
src/platforms/weex/compiler/modules/recycle-list/v-bind.js
src/platforms/weex/compiler/modules/recycle-list/v-for.js
src/platforms/weex/compiler/modules/recycle-list/v-if.js
src/platforms/weex/compiler/modules/recycle-list/v-on.js
test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/attrs.vdom.js
test/weex/cases/recycle-list/attrs.vue
test/weex/cases/recycle-list/text-node.vdom.js
test/weex/cases/recycle-list/text-node.vue
test/weex/cases/recycle-list/v-else-if.vdom.js
test/weex/cases/recycle-list/v-else-if.vue
test/weex/cases/recycle-list/v-else.vdom.js
test/weex/cases/recycle-list/v-else.vue
test/weex/cases/recycle-list/v-for-iterator.vdom.js
test/weex/cases/recycle-list/v-for-iterator.vue
test/weex/cases/recycle-list/v-for.vdom.js
test/weex/cases/recycle-list/v-for.vue
test/weex/cases/recycle-list/v-if.vdom.js
test/weex/cases/recycle-list/v-if.vue
test/weex/cases/recycle-list/v-on-inline.vdom.js
test/weex/cases/recycle-list/v-on-inline.vue
test/weex/cases/recycle-list/v-on.vdom.js
test/weex/cases/recycle-list/v-on.vue

Compile the template twice with different options for weex platform if the `recyclable` flag is passed. Generate both normal render function and `@render` function for `<recycle-list>`.
Function names and arguments are also adjusted in `<recycle-list>` compiler.
If a component has the `recyclable` attribute on the template (`<template recyclable="true">`), weex-vue-loader will pass the `recyclable` option to weex-template-compiler. (https://github.com/weexteam/weex-vue-loader/commit/2b3ed319fa40bdde20f5a284399c1268a4af689d)

feat($compiler): support to generate "@render" function for weex recycle-list

---

src/core/util/env.js
src/core/util/error.js

If the `Vue.config.errorHandler` is not specified, captured errors will be rethrown on the Weex platform. Add more reliable env check in the `logError` could fix it.
Besides, I also add an `inWeex` flag and make the `isAndroid` and `isIOS` flag more reliable.

fix(weex): donot rethrow the captured error on weex platform

---

src/platforms/weex/runtime/modules/attrs.js
src/platforms/weex/runtime/modules/class.js
src/platforms/weex/runtime/modules/style.js
src/platforms/weex/runtime/modules/transition.js

Support batch update styles and attributes on weex platform. Use the `setStyles` and `setAttrs` API if it exists, otherwise, use the origin APIs.
Refs: https://github.com/apache/incubator-weex/commit/30716b672b7ba951796b1b17385e484aaa68f9d9

feat(weex): support batch update styles and attributes

---

package.json
src/platforms/weex/entry-framework.js
src/platforms/weex/util/index.js
test/weex/runtime/framework.spec.js

This feature only compatible with `0.23.1` or higher versions of `weex-js-runtime`.
The `receiveTasks` API is moved to `weex-js-runtime` in order to maintain the consistency of communication behavior between Weex and native.
Also, expose the `registerHook` API in utils and fix spelling mistakes about the "transition".

revert(weex): remove the "receiveTasks" api and support component hook

---

src/platforms/web/runtime/components/transition.js

An out-in transition could get stuck if the child with v-if was not yet shown and then replaced with a different child. In this case, "afterLeave" would never get fired, thus "_leaving" stayed true indefinitely. This was likely to happen with vue-router and asynchronous data loading before the new page is shown.
Fixes #6687.

fix #6687 out-in transition getting stuck with v-if

---

src/compiler/parser/index.js
src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-text.spec.js

Address issue #7048 
I don't have much experience with contributing so any feedback would be very welcome.

test($compile): #7048 warn if both v-model and v-bind:value used on same element

---

src/core/observer/traverse.js

I am using this helper method to seal my objects before passing them to Vue:
```
function makeReactiveAndSeal(obj) {
if (!obj.__ob__) {
Object.keys(obj).forEach((key) => {
Vue.util.defineReactive(obj, key, obj[key]);
});
}
Object.seal(obj);
}
```
This turns silent errors into nice verbose errors, for example when there is a mistake in a Vue template. The function changed by this PR is currently preventing this from working correctly.

fix reactive objects which are sealed

---

packages/vue-server-renderer/types/index.d.ts

TypeScript compiler complains about `not assignable to parameter of type 'RenderCallback'`

Make callback optional when providing context

---

test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/classname.vdom.js
test/weex/cases/recycle-list/classname.vue
test/weex/cases/recycle-list/components/banner.vue
test/weex/cases/recycle-list/components/counter.vue
test/weex/cases/recycle-list/components/poster.vue
test/weex/cases/recycle-list/components/stateful.vdom.js
test/weex/cases/recycle-list/components/stateful.vue
test/weex/cases/recycle-list/components/stateless-with-props.vdom.js
test/weex/cases/recycle-list/components/stateless-with-props.vue
test/weex/cases/recycle-list/components/stateless.vdom.js
test/weex/cases/recycle-list/components/stateless.vue
test/weex/cases/recycle-list/inline-style.vdom.js
test/weex/cases/recycle-list/inline-style.vue
test/weex/helpers/index.js

Adjust the test helper functions of weex, and add more test cases for recycle-list:
+ Binding class names in `<recycle-list>`.
+ Binding inline styles in `<recycle-list>`.
+ Using stateless sub component.
+ Using stateful sub component.
Some test cases couldn't pass yet, I added a comment to them.

test(weex): add more test cases for recycle-list

---

src/platforms/weex/util/index.js

+ Add flow type annotations.
+ Add the `registerComponentHook` and the `updateComponentData` API.

style(weex): update weex utils

---

package-lock.json
package.json
types/options.d.ts
types/test/options-test.ts
types/vue.d.ts

`Component` is too restrictive about `props` type: it either accepts an array or an object, but not both. This makes it illegal to assign `CompoenntOptions` to `Component`. Actually it is a typing bug, but it requires TS 2.6 to find this out. 
So this pull request also bumps the compiler version. It only affects development.
Bumping version also finds another method naming problem in directive test :)
cc @ktsn

fix(types): bump ts version and fix typing bugs

---

src/platforms/weex/entry-framework.js

Make sure the timing of sending the "createFinish" signal is more reasonable, even if using asynchronous rendering (Call `new Vue()` in Promise or timer).

fix(weex): send createFinish signal after root component mounted

---

flow/component.js
package-lock.json
package.json
src/core/instance/init.js
src/platforms/weex/runtime/recycle-list/render-component-template.js
src/platforms/weex/runtime/recycle-list/virtual-component.js
test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/components/editor.vue
test/weex/cases/recycle-list/components/footer.vue
test/weex/cases/recycle-list/components/stateful-v-model.vdom.js
test/weex/cases/recycle-list/components/stateful-v-model.vue
test/weex/cases/recycle-list/components/stateless-multi-components.vdom.js
test/weex/cases/recycle-list/components/stateless-multi-components.vue
test/weex/helpers/index.js

**What kind of change does this PR introduce?** 
Partially implement the virtual component for `<recycle-list>`.  
https://github.com/Hanks10100/weex-native-directive/tree/master/component

feat(weex): WIP implement virtual component

---

src/core/util/options.js
test/unit/features/options/data.spec.js

Fix 7191 - data arg merge

---

src/platforms/weex/compiler/modules/append.js
test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/attrs.vdom.js
test/weex/cases/recycle-list/classname.vdom.js
test/weex/cases/recycle-list/components/stateful-v-model.vdom.js
test/weex/cases/recycle-list/components/stateful.vdom.js
test/weex/cases/recycle-list/components/stateless-multi-components.vdom.js
test/weex/cases/recycle-list/components/stateless-with-props.vdom.js
test/weex/cases/recycle-list/components/stateless.vdom.js
test/weex/cases/recycle-list/inline-style.vdom.js
test/weex/cases/recycle-list/text-node.vdom.js
test/weex/cases/recycle-list/v-else-if.vdom.js
test/weex/cases/recycle-list/v-else.vdom.js
test/weex/cases/recycle-list/v-for-iterator.vdom.js
test/weex/cases/recycle-list/v-for.vdom.js
test/weex/cases/recycle-list/v-if.vdom.js
test/weex/cases/recycle-list/v-on-inline.vdom.js
test/weex/cases/recycle-list/v-on.vdom.js
test/weex/compiler/append.spec.js

**Does this PR introduce a breaking change?** 
Add `append="tree"` attribute on `<recycle-list>` and `<cell-slot>`, as well as the forgotten `<header>`.
Make sure the node of `<recycle-list>` and its children are sent to the native together, otherwise, the native render engine will not know how many templates (`<cell-slot>`) exist in the list.

feat(weex): append as tree by default for recycle-list and cell-slot

---

src/core/vdom/patch.js
test/unit/features/component/component.spec.js
test/unit/modules/vdom/patch/children.spec.js

fix(patch): warn error when children with duplicate key

---

src/server/optimizing-compiler/modules.js

This fixes a double escaping of attribute values in the SSR optimizing
compiler, because literal attribute values get escaped early during the
call to `addAttr` inside `processAttrs` before it is known, if this
attribute will be serialized to an _ssrNode string template.
Later on the _ssrNode string template gets escaped again to preserve
whitespace and this causes double escaping of the whitespace inside the
attribute value.
This approach fixes the problem by undoing the escaping by parsing the
attribute value JSON in `genAttrSegment`, which is the easiest fix to
the problem, but probably not the best.
This fixes #7223 at least for the cases where I encountered the problem.
See #7223 for an in-depth description of the problem and a test-case.
**What kind of change does this PR …

fix(compiler): fix double escaping of ssrNode attribute values (fix #7223)

---

src/core/instance/state.js
src/core/util/options.js
src/core/util/props.js
test/unit/features/options/props.spec.js

When using object for validating props, there are no checks about object content. This may take a long time before noticing that you forget to pass required prop, but there are no warnings with a misprint.
Fail cases:
- Typo in key name `deafult: false` or `require: true`
- Using non-english letter in key name (for example, russian)
P.S.: Will be great to add instance sections names validation, but I have no idea how to solve this (once I spent a lot of time before see that writed `component: {}` section instead …

fix(props): handle misspelled keys on prop validation object

---

flow/component.js
flow/options.js
package-lock.json
package.json
src/core/instance/state.js
src/platforms/weex/runtime/recycle-list/virtual-component.js
src/platforms/weex/util/index.js
test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/components/counter.vue
test/weex/cases/recycle-list/components/lifecycle.vue
test/weex/cases/recycle-list/components/stateful-lifecycle.vdom.js
test/weex/cases/recycle-list/components/stateful-lifecycle.vue
test/weex/runtime/framework.spec.js

+ Override the `_init` and `_update` on the prototype of the VirtualComponent to partially support lifecycle hooks.
+ Simulate native render engine behaviors, and add test cases for testing the lifecycle hooks and data update.

feat(weex): partially support lifecycles of virtual component

---

src/core/vdom/patch.js
src/shared/util.js
test/unit/modules/vdom/create-element.spec.js

fix #7157
Flow still doesn't support `typeof symbol`, a suppression comment is added. 
Also, all usage of `isPrimitive` is checked, additional `String` cast is added for compatibility.

feat(warning): allow symbol as vdom key

---

flow/weex.js
src/platforms/weex/entry-framework.js
test/weex/helpers/index.js
test/weex/runtime/framework.spec.js

Remove the `init`, `reset`, `getRoot` and `receiveTasks` APIs, which are already implemented in the new version of `weex-js-runtime`.
Moreover, the deprecated timer APIs should also be removed when they were supported by native render engines (C++ timers).
Use `createInstanceContext` instead of `createInstance` to create the Vue module instance for each page. The Vue framework only needs to prepare the instance context and no longer execute the js code. The js code will be executed by native render engines.
Add more reliable flow type declarations of Weex instance APIs and DOM APIs, and add type annotations for the entry file.

feat(weex): adjust framework entry APIs and add flow annotations

---

types/test/options-test.ts
types/vnode.d.ts

- Replaced `VNodeChildren` with `VNodeChildrenArrayContents` in its recursive declaration. The current `VNodeChildrenArrayContents` type looks inaccurate because it can include a scoped slot in the returned value of another scoped slot.
- `VNodeChildrenArrayContents` inherits `Array` interface so that we can narrow the type with `Array.isArray` function.

fix(types): make VNodeChildrenArrayContents type more accurate

---

src/compiler/parser/html-parser.js

need escape '-' to prevent being parsed to comment tag in script tag
fix #7298

fix(compiler): change /<!--/ to /<!\--/ (fix #7298)

---

package.json
packages/weex-template-compiler/package.json
src/platforms/weex/compiler/modules/recycle-list/v-bind.js
src/platforms/weex/compiler/modules/style.js
src/platforms/weex/util/parser.js
test/weex/cases/cases.spec.js
test/weex/compiler/parser.spec.js

Required `acorn` and `escodegen` in `weex-template-compiler` to compile expression strings into specified weex native directives. (https://github.com/Hanks10100/weex-native-directive/issues/11)

feat(weex): support to parse object literal in binding attributes or styles

---

.eslintrc
flow/weex.js
src/core/util/env.js
src/platforms/weex/runtime/node-ops.js
src/platforms/weex/util/index.js

Update flow type annotations of Weex to clarify the structure of `weex`, `document`, `WXEnvironment`, `WeexElement` and so on. Also, update the `.eslintrc` to consider `WXEnvironment` as a global object.

chore: update weex flow type annotations

---

types/options.d.ts
types/test/options-test.ts

Fix bugs spotted in https://github.com/vuejs/vue-test-utils/pull/317#discussion_r159149553.
Some type theory shenanigans below:
This pull request allows assigning `ComponentOption` of a Vue subclass to `Component`. The problem is that we used to mark default vm type  as `Vue` in `Component`. However, since `ComponentOption` is contravariant against vm type `V`. The default bound should not be the upper bound `Vue`, but the lower bound `never`.
For a more concrete example, consider this usage:
```ts
interface MyComponent extends Vue {
num: number;
}
const option: ComponentOptions<MyComponent> = {
// a lifetime method
created(this: …
```

fix(types): contravariant generic default in ComponentOption

---

src/core/vdom/create-element.js
test/unit/modules/vdom/create-element.spec.js

fix(vdom): svg inside foreignObject should be rendered with correct namespace (fix #7330)

---

src/platforms/web/runtime/modules/transition.js
test/unit/features/transition/transition.spec.js

Fix transitions on v-show cancelled on next frame (fix #7390)

---

src/core/vdom/modules/ref.js
test/unit/features/ref.spec.js

prevents missing elements when :ref value is "0"
fix #7669

fix(refs): allow ref key to be zero (fix #7669)

---

package-lock.json
package.json
src/core/vdom/patch.js
src/platforms/web/runtime/node-ops.js
src/platforms/weex/runtime/modules/class.js
src/platforms/weex/runtime/node-ops.js
test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/components/stateful-v-model.vdom.js
test/weex/cases/recycle-list/components/stateful.vdom.js
test/weex/cases/recycle-list/components/stateless-multi-components.vdom.js
test/weex/cases/recycle-list/components/stateless-with-props.vdom.js
test/weex/cases/recycle-list/components/stateless.vdom.js
test/weex/cases/render/sample.vdom.js
test/weex/helpers/index.js
test/weex/runtime/class.spec.js
test/weex/runtime/components/richtext.spec.js

**What kind of change does this PR introduce?** 
No longer manage style sheets and class list in vue and weex-js-runtime.
The key modifications are:
1. Add `@styleScope` attribute on each element which value equals the `scopeId`.
2. No longer parse styles from class list, just set `class` attribute directly.
3. Update related test cases.
Refer to https://github.com/Hanks10100/weex-native-directive/issues/14

feat(weex): support sending style sheets and class list to native

---

src/platforms/weex/compiler/modules/recycle-list/component-root.js
src/platforms/weex/compiler/modules/recycle-list/index.js
src/platforms/weex/compiler/modules/recycle-list/recycle-list.js
src/platforms/weex/compiler/modules/recycle-list/v-if.js
src/platforms/weex/compiler/modules/recycle-list/v-once.js
test/weex/cases/cases.spec.js
test/weex/cases/recycle-list/v-else-if.vdom.js
test/weex/cases/recycle-list/v-once.vdom.js
test/weex/cases/recycle-list/v-once.vue
test/weex/compiler/append.spec.js
test/weex/helpers/index.js

+ Support to compile `v-once` and add a test case.
+ Generate `@templateId` on the root element of each component.
+ Add `binding-expression` attribute on `<recycle-list>`.
+ Fix the compile result of `v-else-if` and `v-else`.

fix(compiler): update weex recycle-list compiler

---

src/core/observer/index.js

The defineReactive gets the property of the object, only if it has no getter
fix #7280

fix(core): fix defineReactive unnecessary getters call fix #7280

---

src/core/util/env.js

In Weex, `global` does exist, but `global.process` does not. I think it's more reliable to exclude Weex platform when detecting the ssr env.
[edits: minor grammar edits]

Fix the env detection of server side rendering

---

src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-text.spec.js

Fix #7404: skip v-model & value binding collision check with dynamic type binding

---

src/shared/util.js

Simple refactor bind function for easy revert.
Custom bind implementation performance is lower than native. ( https://jsperf.com/vue-bind-perf )
issue link: https://github.com/vuejs/vue/issues/7408

fix(core): Use native bind function instead of own (fix #7408)

---

src/core/instance/inject.js
test/unit/features/options/inject.spec.js

The issue was caused by the [`in` operator check](https://github.com/vuejs/vue/blob/dev/src/core/instance/inject.js#L55) to see if an injection exists in a parent provide.
In the particular Issue, the injection didn't work because the the Symbol polyfill adds a setter to the Object prototype for every Symbol created and the `in`-operator check evaluated to true on any object inheriting Object. [Demo](http://jsfiddle.net/hirokiosame/dronjdzm/23/)
However, I'm thinking the implications of using `in` may be further reaching as it could have been any native prototype property. [Here](http://jsfiddle.net/hirokiosame/dronjdzm/24/) I demonstrate using the string `'constructor'` leads to unexpected injection behavior.
Although this fixes #7284, I am framing this as a fix for prototype properties …

fix(inject): hasOwn instead of 'in' (fix #7284)

---

src/compiler/parser/filter-parser.js
test/unit/modules/compiler/codegen.spec.js

Fix #7544
Make sure no extra , is added at the end of the call so it also work with older browsers

fix(codegen): support filters with () in older browsers

---

types/options.d.ts
types/test/options-test.ts

Looks like `listeners` type is missing on the `RenderContext` of functional component render function. So I just add it.
https://vuejs.org/v2/guide/render-function.html#Functional-Components

fix(types): add missing `listeners` type on RenderContext

---

types/options.d.ts
types/test/options-test.ts

Since we can write a template of functional component in SFC, the `render` option of functional component can be omitted now.

fix(types): make render option in functional components to optional

---

src/core/util/next-tick.js

chore: update wording in next-tick.js, unifies the term of 'microtask' and '(macro) task'

---

types/options.d.ts
types/test/options-test.ts

`errorCaptured` lifecycle hook actually receives some parameters. https://vuejs.org/v2/api/#errorCaptured

fix(types): fix wrong errorCaptured type

---

test/unit/modules/observer/dep.spec.js

Tests coverage extending
Hey folks, I like autotests and would like to start to contribute to `vue` because heard many positive reviews about it.

chore: add unittests for core/observer/dep

---

src/core/instance/state.js

```
return createWatcher(vm, expOrFn, cb, options)
```
They are actually the same thing, but use different variable name.

Style: update variable name

---

src/core/observer/index.js

docs: fix grammar mistake

---

types/options.d.ts
types/vue.d.ts

Background: 
https://github.com/vuejs/vetur/issues/676
https://github.com/vuejs/vetur/issues/627#issuecomment-357124941
TypeScript cannot give reasonable completion for `Vue.extend`. For example, `methods`, `data` will not appear in completion list.  This is caused by the intricate overloading resolution in compiler host. https://github.com/Microsoft/TypeScript/issues/8005.
This problem will probably not fixed in foreseeable future. So we can work around this by placing normal component option before functional component. In most case, normal component option provides better completion. However, this will break type inference for functional …

fix(types): prefer normal component over functional one

---

src/core/instance/lifecycle.js
src/core/instance/state.js
src/core/observer/dep.js
test/unit/features/options/data.spec.js

fix(core): props getter shouldn't collect dependencies during initialization of data option (fix #7573)

---

test/unit/modules/vdom/create-element.spec.js

test(vdom): create-element should work properly with vnode reference in :class or :style

---

src/platforms/web/server/directives/show.js
test/ssr/ssr-string.spec.js

web/server/directives/show just add style.display='none', no matter style is object or array; If
style is an array, it will lost additional property while tranformed into object by
shared/utils#toObject;
fix #7813

fix: add v-show style in ssr if style is binding to an array

---

src/core/observer/index.js
test/unit/modules/observer/observer.spec.js

Limiting set/delete to objects and arrays is overly restrictive; for example, there's no problem in setting properties on functions.  I just changed the condition to what the original PR's description claimed and clarified the warning message.

fix(core): Make set/delete warning condition for undefined, null and primitive values more precise.  Corrects #7452

---

src/core/instance/proxy.js
test/unit/features/instance/render-proxy.spec.js

It's feasible that someone might ask if something other than a string is
in the proxy such as a `Symbol` that lacks a `charAt` method.  This aligns
the implementation with the `getHandler`.
This issue was discovered when using `vue-test-utils` and the associated test helpers it provides.  Ref: https://github.com/vuejs/vue-test-utils/issues/452

fix: correct the `has` implementation in the `_renderProxy`

---

src/core/instance/state.js

Through the processing of the `mergeOptions` function, the type of `vm.$options.data` is either a `function` or `undefined`. And in the `initState` function has filtered out the possibility of `undefined`, so in the `initData` function `vm.$options.data` must be a `function`

refactor: remove unnecessary checks

---

types/index.d.ts

Users using Vue from e.g. the CDN might be using the global `.Vue` without importing the module.
See https://www.typescriptlang.org/docs/handbook/modules.html for details on the syntax

Add UMD global declaration to index.d.ts

---

scripts/release-weex.sh
scripts/release.sh

Hi,
I fixed various things spotted by shellcheck.

Clean shell scripts

---

src/core/instance/lifecycle.js
src/core/observer/scheduler.js
src/core/observer/watcher.js
src/platforms/web/runtime/components/transition-group.js
test/unit/features/options/lifecycle.spec.js

fix: beforeUpdate should be called before render and allow state mutation

---

flow/options.js
src/core/instance/init.js
src/core/instance/lifecycle.js
src/core/vdom/create-component.js
src/core/vdom/patch.js

fix: invoke component node create hooks before insertion

---

src/core/instance/state.js
src/core/observer/watcher.js
test/unit/features/options/computed.spec.js
test/unit/modules/observer/watcher.spec.js

perf: avoid unnecessary re-renders when computed property value did not change

---

src/core/observer/index.js

After #7302, there's an asymmetry in `defineReactive` for properties that have both a getter and a setter.  On initial creation, the value returned by the getter is not made reactive since #7302 makes sure not to fetch it and `observe(val)` is a no-op.  However, if the value is set again after the property has been made reactive, it is made reactive as well since `observe(newVal)` in `set` is not gated on missing a getter.  (The premise justifying the change in …

fix(observer): invoke getters on initial observation if setter defined. Corrects #7302

---

src/compiler/codegen/events.js

Closes #7880
IE11 and Edge use "Esc" as key name, other browsers use "Escape".
I was able to test on Edge 16/15/14 and IE11.
- More reference: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5290772/
- Reproduction link: http://codepen.io/anon/pen/QjxPGB

fix(codegen): support IE11 and Edge use of "Esc" key (close #7880)

---

src/core/vdom/vnode.js

This fixes a crash during SSR, where a parent functional component is using an async component in the render function. If the prop is not copied, `renderAsyncComponent` crashes during rendering. Looks like this bug was introduced in 62a922e865f5e578f67b386cb614abfc173d7851

Adds missing `asyncMeta` during VNode cloning

---

src/platforms/weex/runtime/modules/class.js
test/weex/cases/cases.spec.js
test/weex/cases/render/class.vdom.js
test/weex/cases/render/class.vue

Object syntax class is supported in Weex now:
```html
<div v-bind:class="{ active: isActive }"></div>
```

feat(weex): support object syntax of class

---

package.json

This PR adds the `"sideEffects": false` property in vue's `package.json` file. This allow's webpack (for those who want to opt-in to requiring vue's original source files (instead of the flattened esm bundles) and want to remove flow type through a babel-transform, then this will allow webpack to aggressively ignore and treeshake unused exports throughout the module system. 
In many cases this can yield hidden and surprising build time improvements and size reductions in the case that …

chore(package.json): Add sideEffects: false field in package.json

---

src/platforms/web/server/util.js

refactor: ignore control-regex lint for unsafeAttrCharRE

---

src/core/util/props.js
test/unit/features/options/props.spec.js

Here is my solution for #7764.
I'm sure it's far from perfect, so I'll be happy to see any suggestion or advice 👍

feat(warn): make the warning messages more explicit (close #7764)

---

src/server/optimizing-compiler/modules.js
test/ssr/ssr-string.spec.js

This fixes a double escaping of literal class values in the SSR optimizing compiler by unescaping the value in `genClassSegments`.
This bugfix is very similar to https://github.com/vuejs/vue/pull/7224. Literal class values get escaped twice during [`transformNode`](https://github.com/vuejs/vue/blob/79c0d7bcfbcd1ac492e7ceb77f5024d09efdc6b3/src/platforms/web/compiler/modules/class.js#L25) and [`flattenSegments`](https://github.com/vuejs/vue/blob/79c0d7bcfbcd1ac492e7ceb77f5024d09efdc6b3/src/server/optimizing-compiler/codegen.js#L240), causing the double escape.
fix #7859 
**The PR …

fix(ssr): fix double escaping of staticClass values (fix #7859)

---

types/options.d.ts
types/test/options-test.ts

Currently, the return type of `default` option is annotated with `object` since it is used for generating fresh object for each component instance. But there is another use case for `default` option of function in [portal-vue](https://github.com/LinusBorg/portal-vue) which is for dynamically generating unique value as default.
https://github.com/LinusBorg/portal-vue/blob/develop/src/components/portal.js#L16
The current typing breaks `this` type inference when the `default` function returns non-object type. I just relaxed the return type to `any` to avoid breaking the inference.

fix(types): relax the return type of props default option

---

src/core/observer/index.js

Please check: https://github.com/vuejs/vue/issues/7280#issuecomment-379529594

refactor: make the set method more reasonable

---

types/options.d.ts
types/test/options-test.ts
types/vnode.d.ts

Prevents `Property 'oldValue' is missing in type '{ name: string; value: string; }'.` when using directives in a render function (see test). 
There should probably actually be three different `VNodeDirective`s:
- In `h('', data)` - mostly optional, not readonly
- In `VNodeData` (returned from createElement) - normalised, not readonly
- In `DirectiveFunction` - the current definition (before this change)

fix(types): make VNodeDirective properties optional, fix #8013

---

src/shared/util.js

Improvements that apply to all comments:
- Consistent use of periods
- Consistent use of commas
- Consistent capitalization
- Correct use of articles (a, an, the)
Improvements to specific comments:
- Correct pluralization in the description for helper functions
- Re-word for clarity and break into shorter sentences the description
for `polyfillBind` function
- Re-word for clarity the description for `genStaticKeys` function
- Add a previously missing description for `looseIndexOf` function
Fixes: https://github.com/vuejs/vue/issues/8528

fix (shared-utils): Improve readability and consistency in code comments (fix #8528)

---

src/platforms/web/runtime/components/transition.js

refactor(transition): replace nested closure with static ones

---

src/platforms/web/runtime/class-util.js

Cache the whitespace regex to improve performance

refactor(class-util): cache whitespace regex

---

src/sfc/parser.js
test/unit/modules/sfc/sfc-parser.spec.js

I'm developing some editor extension which can highlight styles and noticed if there are root indentation, the highlight position is broken. I've found this is because vue-template-compiler deindents SFC contents even when `pad` option is specified.
I've changed this behavior to only deindent when `pad` option is not specified.
I have no idea why the template option is not padded but it would be needed to provide correct position of template block? If I'm missing …

fix(sfc): avoid to deindent when pad option is specified

---

src/shared/util.js
test/unit/features/directives/model-select.spec.js

Fix #7928
thanks to @w3cj for the initial version. This one is using getTime instead of toUTCString because it
is much faster to compare
Initially, I wanted to keep your commit but it wasn't yours (somehow) from a git perspective, so you didn't appear in the history 🙁 , I ended up creating a single new commit

fix(shared): check dates in looseEqual

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

refactor: add empty v-bind warning(re #7973)

---

scripts/config.js

Update config.js use string literals

---

src/platforms/web/runtime/modules/attrs.js

hi
I encountered the same problem(#7138) during development.
In my case, it occurred in the input tag, not the textarea, so I added conditional statements.
after adding the conditional statement, I confirmed that the problem was also resolved in the input tag.

Fix: block unnecessary input event on input tag placeholder in IE

---

src/compiler/codegen/index.js
test/unit/modules/compiler/codegen.spec.js
test/unit/modules/compiler/parser.spec.js

close #8041
I don't believe this is breaking as content inside of `v-pre` is considered to be static. _However_ it does change the outputted static content in the case where a `<template>` tag is labeled with `v-pre` or inside of a `v-pre` element.
I pushed a 'compiled' version of this to a different branch to show the working behavior on jsFiddle. The original fiddle from issue #8041: https://jsfiddle.net/zct418xa/1/
A fiddle with the updated behavior using …

fix #8041: templates inside v-pre should be rendered to HTML

---

src/server/template-renderer/index.js
test/ssr/ssr-template.spec.js

fix(server): use path.posix.join to generate public path, fix #8167

---

types/options.d.ts
types/test/options-test.ts

allow functional components to return multiple VNodes (fix #8191)

---

types/test/options-test.ts
types/vnode.d.ts

See #4035 and #8225
`refInFor` is also mentioned in https://github.com/vuejs/babel-plugin-transform-vue-jsx#difference-from-react-jsx and can be seen in the generated code on https://vuejs.org/v2/guide/render-function.html#Template-Compilation

fix(types): add refInFor to VNodeData

---

src/compiler/parser/index.js

**It is not a bug, but it will be more friendly to code output.** In terms of semantics, alias is a variable. It should remove spaces.
**before**
**after**

fix(compiler): remove the extra space of v-for alias

---

src/platforms/web/runtime/transition-util.js

`jsdom` returns `undefined` from `style` instead of empty string.
```
$ node
> const jsdom = require("jsdom");
undefined
> const { JSDOM } = jsdom;
undefined
> const dom = new JSDOM(`<!DOCTYPE html><p style="color: red;">Hello world</p>`);
undefined
> dom.window.document.querySelector("p").style
CSSStyleDeclaration {
'0': 'color',
_values: { color: 'red' },
_importants: { color: '' },
_length: 1,
_onChange: [Function] }
> dom.window.document.querySelector("p").style.color
'red'
> dom.window.document.querySelector("p").style.unexisted
undefined
>
```
So a solution is to do like that:
``` …
```

Need judge styles[transitionProp 'Duration'] is undefined (fix #7444)

---

src/compiler/parser/html-parser.js

```js
const value = '' || somevalue
```
is the same with
```js
const value = undefined || somevalue
```

refactor: remove redundant code in html-parse

---

src/platforms/web/runtime/components/transition-group.js

If in your list you have transitions on the nested elements, they will trigger the transitionend events that will cause finishing of transition-group's transition.

fix(transition): transition-group should only listen for first-level children's end events

---

src/compiler/helpers.js

Here is an example: https://codesandbox.io/s/m5j9wk0l4p
Using both the `right` modifier and the `once` modifier in a click event will invalidate the `contextmenu` event.

fix: support for the use of modifiers such as click.right.once

---

src/platforms/web/runtime/transition-util.js

Old versions of [Chromium](https://www.chromium.org/) (below 61.0.3163.100) [formats floating pointer numbers in a locale-dependent way, using a comma instead of a dot](https://bugs.chromium.org/p/chromium/issues/detail?id=720222).
This PR makes toMs function parse it correctly, preventing unexpected behaviors.

update toMs function. fix #4894

---

src/compiler/codegen/index.js
test/unit/features/options/functional.spec.js
test/unit/modules/compiler/codegen.spec.js

Normalize nested arrays when using functional components with v-for.

fix(compiler): normalize nested arrays in v-for(fix #8468)

---

src/core/instance/state.js
test/unit/features/error-handling.spec.js

As stated in the [related issue](https://github.com/vuejs/vue/issues/8567), the handle callback call should be wrapped in a try/catch that explicitly calls handleError.
fix #8567
This is my first PR so feel free to provide feedback or request modifications both in the code and the PR itself! 😄

fix(#8567): handle errors on immediate watchers

---

src/core/vdom/create-functional-component.js
src/core/vdom/vnode.js

Used in https://github.com/vuejs/vue-devtools/pull/719 to display prop values in component inspector.

feat: Store functional render context on vnode in development

---

src/server/webpack-plugin/server.js

If we config `chunkName` as `'[name].js?v=[chunkhash]'`, the previous regex cannot match the js assets in webpack plugin, so use `isJS` to perfect match files
Pr will aslo resove https://github.com/nuxt/nuxt.js/issues/3387

fix: check js assets more accurate in ssr webpack plugin

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

We can find this error at compile time.

fix(#8730): Improve error reporting

---

src/core/vdom/helpers/resolve-async-component.js
test/unit/features/transition/transition-mode.spec.js
test/unit/modules/vdom/create-component.spec.js

fix(component): clean up memory leak after loading async component completes (fix #8740)

---

src/core/util/options.js
test/unit/features/global-api/extend.spec.js

fix #8865: skip mixins and extends if child is already merged

---

src/core/vdom/patch.js
test/unit/modules/vdom/patch/children.spec.js

fix #8832: duplicate keys detected not warned

---

src/compiler/parser/html-parser.js
test/unit/modules/compiler/parser.spec.js

fix(compiler): should keep newline after unary tags in <pre> (fix #8950)

---

src/core/util/options.js

Fixes https://github.com/vuetifyjs/vuetify/issues/5633
I've been unable to reproduce this in isolation, but have run into it several times in the past. This check should also reduce unnecessary calls to `mergeData`, I noticed thousands of instances of identical objects being merged that didn't cause errors.

fix(mergeData): skip recursive call if values are identical

---

types/test/vue-test.ts
types/vue.d.ts

to be able to define `$el` as `SVGElement`

fix(types): update the type definition of $el property

---

types/test/options-test.ts
types/vue.d.ts

When working directly with render functions in TypeScript / tsx, currently the following code is unsafe and unchecked by the ts compiler:
```ts
this.$sopedSlots.default() // default can be undefined
```
The change in this PR makes TypeScript complain about the unsafe access accordingly and the code has to be expressed in a way that prevents calling an undefined function, e.g.:
```ts
( this.$scopedSlots.default || ( () => 'default value' ) )( props )
```

Typings: Improve $slots and $scopedSlots type to prevent unchecked access to undefined

---

src/core/util/env.js

In wechat mini-program, `global` does exist, but `global['process']` does not:

Fix the env detection of ssr for wechat mini-program

---

types/options.d.ts

style(types): fix typo

---

src/core/instance/state.js
test/ssr/ssr-string.spec.js

fix(ssr): computed properties first argument

---

src/core/observer/index.js

chore: fix grammar in core/observer/index.js comments

---

src/compiler/codegen/index.js
test/unit/modules/compiler/codegen.spec.js

add wrapping paranthesis for v-if conditions
the generated code for elements with template in scopedslots was wrong when multiline v-if starting
with a newline was used
fix #9114

fix #9114 correct the compiled code for multiline v-if in scoped slots

---

src/core/instance/events.js
src/core/vdom/helpers/update-listeners.js
src/platforms/web/runtime/modules/events.js
src/platforms/weex/runtime/modules/events.js
test/unit/features/directives/on.spec.js

fix: correctly remove once listener with v-if

---

types/test/options-test.ts
types/vnode.d.ts

see #8946
- scoped slots can return a single VNode if `<template>` is not used
- `$scopedSlots` needs to be able to be passed down to children (https://github.com/vuetifyjs/vuetify/blob/8a1b48304b64ff001e9feda3c64a23883448d76b/packages/vuetify/src/components/VTreeview/VTreeviewNode.ts#L262)

fix(types): correct scopedSlot types

---

packages/vue-template-compiler/package.json
packages/vue-template-compiler/types/index.d.ts
packages/vue-template-compiler/types/test.ts
packages/vue-template-compiler/types/tsconfig.json

I just remembered I wrote `vue-template-compiler` typings for my own project when seeing [`component-compiler-utils` types](https://github.com/vuejs/component-compiler-utils/blob/master/lib/types.ts) 😄 
It would be convenient for anyone who writes static analysis / customized compiler / build tools in TypeScript.

feat(types): add vue-template-compiler types

---

types/options.d.ts

The current type definition for `ComponentOptions` does not have a definition for [async component factories](https://vuejs.org/v2/guide/components-dynamic-async.html) and as such causes errors when using the syntax with [vue-class-component](https://github.com/vuejs/vue-class-component).

types: add AsyncComponentFactory type

---

types/test/tsconfig.json
types/test/vue-test.ts
types/vue.d.ts

Fix https://github.com/vuejs/vue-class-component/issues/294
Mixing `this`, `interface`, `extends` and `new` signature seems to be hairy in TypeScript. It is better to not rely on `this`.

fix(types): avoid `this` in VueConstructor signature

---

types/test/options-test.ts
types/vnode.d.ts

fixes #8498
Still not sure about `VNodeComponentOptions.children`, I don't know if that gets normalised or not.

fix(types): broaden VNodeChildren, fix #8498

---

test/unit/features/directives/model-text.spec.js

I think the intention of this test case is to prove v-model's event is handled before other v-on events. i tried to revert code associated with this test and it passed. so original one seems to fail to prove that (correct me if i am wrong).

fix(test): change model text's priority case

---

src/server/template-renderer/index.js
test/ssr/ssr-template.spec.js

re #7479
Please let me know if anything is missing. I guess I should add documentation too, but I'm not sure where I can edit the SSR doc.
This resolves #7479.

feat(ssr): Add 'nonce' option to context for ssr outlet script, fix #7479

---

src/platforms/web/runtime/modules/dom-props.js

Currently for older browsers (IE9~IE11) we cannot use `v-html` on SVG elements because they don't support `innerHTML` for SVG elements. While actually we can fix this without much effort and make it “just works”. As `innerHTML` is defined for `Element` interface (which `SVGElement` is derived from) [in the latest spec](https://w3c.github.io/DOM-Parsing/#dfn-innerhtml), I think it's reasonable to add this for `v-html`.
Related issues: #5310 #5756
Since it's a …

feat: support v-html for SVG elements

---

src/core/util/options.js
test/unit/features/options/inject.spec.js

Fixes merging multiple provides using Symbols
fix #7923
The test I added only passes in an environment with symbols (since it's handling a case that fails with symbols). This fails when the test is executed with Phantom, since it doesn't have Symbol support natively or with a polyfill, but passes in Chrome.
I can add babel-polyfill but seemed excessive for one test. Wanted to know how to move forward with that one before making any drastic changes to making it …

fix(provide): Merges symbol provides

---

src/shared/util.js
test/unit/features/directives/html.spec.js
test/unit/features/directives/text.spec.js

**Description:**
Hi, 
When interpolating an object, it uses the JSON.stringify method instead of toString, which is normally the proper method to set a way to convert an object to a string. 
This PR allow you to use your custom `toString` method to render your object if it exists. It's tested (I've also added a test for toJson), and it should not be a breaking change.
Thanks you for your amazing work folks, and see you in Paris next month!

fix #8093: Use custom toString method when interpolating objects if implemented

---

src/compiler/parser/index.js
src/shared/util.js
test/unit/features/directives/bind.spec.js

Addresses #6428 and https://github.com/vuejs/vuejs.org/issues/1648

Adds handler for kebab-case event for v-bind:sync; fix #6428

---

src/core/instance/render-helpers/render-list.js
test/unit/features/directives/for.spec.js

Adds support for iterable object implementing [Symbol.iterator]()
It shouldn't have an impact for existing code because non iterable objects are not impacted.
Vue will have the same behaviour than a for...of expression for iterables. (actual interest for using iterables)
Allows us to pass an iterable directly to a template without giving internal properties or converting it to an array
I wrote 4 new tests. No existing tests needed changes.
All tests passed. I ran …

Add iterable supports for v-for 

---

src/core/vdom/create-functional-component.js
test/unit/features/options/functional.spec.js
types/options.d.ts
types/test/options-test.ts

Related #5381
We discussed this being added to 2.6.
It is nothing new, as `scopedSlots` already exist on `data`. The only reasons to add it are convenience and consistency with `slots` (although `slots` is a function).
If you have arguments for or against this feature, please share them 🙂 

feat(functional): add scopedSlots to context in functional components

---

src/core/util/options.js
test/unit/features/options/mixins.spec.js

fix(#9198): fix merged twice bug when passing extended constructor to mixins

---

src/core/vdom/helpers/resolve-async-component.js
test/unit/modules/vdom/create-component.spec.js

fix(async component): memory leak after synchronous async loading (fix #9229)

---

src/server/create-renderer.js
src/server/template-renderer/index.js

@yyx990803 I've found a solution to #9205 
It's a very simple addition, to the `vue-server-renderer` package that has tonnes of use-cases and actually makes the `vue-server-renderer` much easier to use, as it provides a template function to the bundle renderer template compiler.
This isn't a breaking change and doesn't really need any tests, as it is a user-provided function
It would be amazing if this could be added in **2.6**, so I could use it in my package
1. …

[feature] allow template to be function in vue-server-renderer

---

flow/compiler.js
src/compiler/codegen/index.js
src/compiler/parser/index.js
src/core/instance/lifecycle.js
src/core/instance/render-helpers/resolve-slots.js
src/core/vdom/helpers/normalize-scoped-slots.js
test/unit/features/component/component-scoped-slot.spec.js
test/unit/modules/compiler/codegen.spec.js

Ensure that state mutations that only affect parent scope only trigger parent update and does not affect child components with only scoped slots.
Implications:
- For optimal performance, scoped slots should always be preferred. (In v3 all slots are unified to work like scoped slots so that will be the default)
- In 2.6, any slots using the new `v-slot` syntax are compiled as scopedSlots internally. This doesn't affect the child if it's using template, since `<slot/>` can render both scoped and normal slots, but if the child is using render functions, it is recommended to always use `this.$scopedSlots`. It is safe to do so in 2.6 since all normal slots are proxied on `this.$scopedSlots` as well.
- Unfortunately, any child components with static slot content still need to be forced updated. …

perf: improve scoped slots change detection accuracy

---

src/platforms/web/runtime/modules/style.js
test/unit/features/directives/style.spec.js

The [documentation](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty#Parameters) states that the first parameter for `setProperty` must be hyphenated.
closes #9382

style does not work with zIndex (fix #9382)

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

in SFC templates, we are alloed to have comments on the root node. We are not alloed to do so if we
try to extract these comments. This commits ignores the root components instead of breaking.
#9407

fix(vue-template-compiler): allow comments on the root node in templates (fix #9407)

---

src/compiler/parser/html-parser.js

pretty much everything in the ruby world, html escapes single quotes
https://github.com/ruby/ruby/blob/trunk/lib/cgi/util.rb#L30
so, for example, haml pre-processed vue templates will have single quotes escaped

decode single quotes in html attributes

---

src/compiler/codegen/index.js
test/unit/modules/compiler/codegen.spec.js

The generator function for inline templates `genInlineTemplate ` did not prevent the generation of code when an invalid template was being introduced. 
The solution introduced is verifying the existence of the first child before checking for its type, this should prevent the application from crashing trying to access attributes in an `undefined` child variable.
closes #9361
<details>
<summary>Index HTML</summary>
```HTML
<!DOCTYPE html>
<html>
<head>
<meta …
```

fix inline-template crashing (fix #9361)

---

src/platforms/web/runtime/modules/attrs.js
test/unit/features/directives/model-text.spec.js

Before this fix, the workaround for #9042 was to provide null or false value instead of empty string: `:placeholder="placeholder || null"`. 
The fix from #7138 was incomplete as it did not account for the case when placeholder attribute exists but is empty and the bug is **not** triggered in IE.
A new test case ensures the first triggered event does not get blocked.

fix #9042, #7138: handle empty placeholder case in IE

---

src/core/vdom/create-component.js
test/unit/features/directives/model-component.spec.js

Fixes #9330 , see that for details.

fix(v-model): add value to $attrs if not defined in props (fix #9330)

---

types/vue.d.ts

```ts
import Vue from 'vue';
console.log(Vue.version)
```
currently throws an Error with: `Property 'version' does not exist on type 'VueConstructor<Vue>'.`
My PR fixed that...

fix(types) add exported version to type definiton

---

src/core/util/error.js
test/unit/features/options/errorCaptured.spec.js

fix vuejs/vuex#1505
The original issue is https://github.com/vuejs/vuex/issues/1505
When we touch some observables in `errorCaptured` hook, it is registered as dependency of the rendered component. Then the infinite rendering loop happens if we update the value inside the hook.
Updated reproduction which does not have Vuex store is here. https://codesandbox.io/s/ypvy7zn9xx

fix: avoid possible infinite loop by accessing observables in error handler (fix vuex#1505)

---

src/core/util/error.js
test/unit/modules/util/invoke-with-error-handling.spec.js

fixed #9511 
In some cases, invokeWithErrorHandling will have nested calls, and Promise will independently catch multiple times, resulting in multiple calls to handleError.
Look at a sample code：
``` javascript
var p = Promise.reject('some err');
p.catch(() => console.log('1'));  // p = p.catch(...)
p.catch(() => console.log('2'));
```
The above code will output 1 and 2, but if you reassign the first catch call to p, it will not output 2.

fix(#9511): avoid promise catch multiple times

---

src/compiler/parser/index.js
test/unit/features/options/directives.spec.js

Fixed issue #9577.
The old modifier matching pattern is `/\.[^.]+/g`, It does not take into account that dynamic arguments may contain `.`，so I updated it and hope it is correct.
code example:
``` {javascript}
const before = /\.[^.]+/g;
const after = /\.[^.\]]+(?=\.|$)/g;
let s = 'name:[a.b].c.d';
console.log(s.match(before)); // [".b]", ".c", ".d"]
console.log(s.match(after));    // [".c", ".d"]
```

fix(#9577): support deep object as dynamic arguments

---

src/compiler/parser/html-parser.js
src/core/util/lang.js
src/core/util/options.js

fix: avoid compression of unicode sequences by using regexps, closes #9456 

---

types/test/options-test.ts
types/vnode.d.ts
types/vue.d.ts

Scoped slots are normalised to `VNode[]`, but they should still be able to return a bare string or VNode when used in a render function. 
https://codepen.io/anon/pen/BMXvme?editors=1010

fix(types): allow scoped slots to return a single VNode

---

src/core/vdom/helpers/resolve-async-component.js

I have not heavily tested this in a lot of circumstances. The async part of it almost broke my brain ^^ But tests are passing, so... ¯\_(ツ)_/¯

fix #9571, rendering async components after initial context was destroyed

---

src/compiler/parser/html-parser.js
src/compiler/parser/index.js
test/unit/modules/compiler/compiler-options.spec.js

End location for incomplete tags are missing, which makes error message looks weird:
```
tag <incomplete-tag> has no matching end tag.
2  |  <div>
3  |    <div>
4  |      <incomplete-tag>
|      ^^^^^^^^^^^^^^^^
5  |    </div>
|  ^^^^^^^^
6  |  </div>
|  ^^^^^^
```
**Expected:**
```
tag <incomplete-tag> has no matching end tag.
2  |  <div>
3  |    <div>
4  |      <incomplete-tag>
|      ^^^^^^^^^^^^^^^^
5  |    </div>
6  |  </div>
```

fix(compiler): set end location for incomplete elements

---

.github/CODE_OF_CONDUCT.md
.github/COMMIT_CONVENTION.md
.github/CONTRIBUTING.md
benchmarks/ssr/README.md
benchmarks/uptime/index.html
dist/README.md
packages/vue-template-compiler/README.md

- [ x] No
- [] New/updated tests are included

docs: fix spelling and grammatical errors

---

types/options.d.ts
types/test/vue-test.ts
types/vue.d.ts

Fixed `RenderContext.scopedSlots` types bug

---

src/core/instance/render-helpers/bind-object-props.js
test/unit/features/directives/bind.spec.js

Fix #9641: v-bind object should be overridable by single bindings

---

src/core/observer/scheduler.js

The previous detection code compared time stamps based on Date.now()
which are not monotonic, so the check could fail due to clock skew or
adjustments.
This fix changes the check to compare against performance.now() if it is
supported, because it is monotonic (strictly increasing).
See the discussion in #9632 for additional info.
This needs to be backported to the 2.6 branch.

fix(scheduler): getNow detection can randomly fail (fix #9632)

---

src/server/template-renderer/create-async-file-mapper.js

Fix https://github.com/nuxt/nuxt.js/issues/5190
Since #7902 has already implemented `initial` and `async` for css, so make `fileMapper` only include async `css` files same as `js` files for avoiding duplicate `style` tags.

fix: not push non-async css files into map

---

src/core/vdom/helpers/resolve-async-component.js
test/ssr/ssr-string.spec.js

fix(ssr): fix nested async functional componet rendering

---

examples/modal/index.html
src/platforms/web/runtime/modules/transition.js
test/unit/features/transition/transition.spec.js

fixed #9628 
Transition inside child component with v-if should be no enter-transition, it depend on appear attribute.

fix(transition): looking up `context` of transition

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

fix: whitespace: 'condense' should honor <pre> tag as well

---

types/options.d.ts
types/test/options-test.ts

fix(types): allow using functions on the PropTypes (#9692)

---

src/core/vdom/helpers/resolve-async-component.js
test/unit/features/component/component-async.spec.js

component-async.spec.js now captures information about all created, triggered and cleared timeouts and verifies after the test that they have been cleared. 
Should fix #9648

fix(core): cleanup timeouts for async components (fix #9648)

---

.github/CONTRIBUTING.md

docs(contributing): fix a grammar error

---

src/compiler/parser/html-parser.js

- [x ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
The licensing in src/compiler/parser/html-parser.js is described as "Mozilla Public License", which will cause flags of concern for some reviewers as it takes Vue from being an MIT licensed project to a project containing copyleft licensing. This is unnecessary as the original code appears to have an option of three licenses. I've updated the text to …

Improving license clarity of simplehtmlparser.js

---

packages/weex-vue-framework/factory.js
src/core/vdom/patch.js

chore: remove useless parameter to the function removeVnodes (#9910)

---

src/core/vdom/create-element.js
test/unit/features/directives/on.spec.js

Currently if we have a `.native` modifier applied to event handler on native HTML element, it will break the handler (you can find the minimal reproduction [here](https://codesandbox.io/s/m718j536yp)).
We had a discussion about it with @chrisvfritz and it was decided it would be a good solution to add a console warning for this case. This way we can warn people they are using `.native` incorrectly: it should be used only on components not on elements.
An ideal …

feat: add warning when .native modifier is used on native HTML elements

---

src/compiler/error-detector.js
src/compiler/parser/index.js
test/unit/features/component/component-scoped-slot.spec.js

The Vue doc says that one can use destructuring props with fallback value as v-slot's value.
Actually, this will cause a warning.

fix(compiler): Remove the waring for valid v-slot value

---

types/index.d.ts
types/test/tsconfig.json
types/test/umd-test.ts
types/umd.d.ts

In the current declaration, `index.d.ts` has `export as namespace Vue` which exposes all exported types in `index.d.ts` in global namespace. So the user can access them by just writing like `Vue.ComponentOptions` without import statement.
But this declaration is actually not correct because the `Vue` constructor type is declared under `default` which is correct in ESModule bundle but UMD bundle.
```ts
new Vue({}) // This provides compilation error in current type. …
```

fix(types): fix global namespace declaration for UMD bundle

---

src/compiler/parser/html-parser.js
src/core/instance/render-helpers/bind-dynamic-keys.js

chore(typo): fix typo in comments

---

packages/vue-server-renderer/package.json

This is for vue-server-renderer
https://github.com/lodash/lodash/pull/4336

fix(security) upgrade lodash.template

---

src/compiler/error-detector.js

a spelling mistake

---

benchmarks/uptime/index.html

This PR replaces the shorthand `flex-flow` with the right long version `flex-wrap`.

fix: set only flex-wrap

---

README.md

I've recently send a PR to vuejs.org with a .png version of the Fastcoding Inc logo. When/if it's merged, change this .svg link to .png.
It's just one logo-link in the README that's a svg, all other are png.

Fastcoding Inc broken icon

---

package.json
packages/vue-server-renderer/package.json
yarn.lock

Since I couldn't find the reason for pinning `webpack` at https://github.com/shakir-abdo/vue/pull/112/commits/bb0aab664c52006ff79d0802631cf59e65fbbe0d I just upgrade it. I've done it due to `webpack#terser-webpack-plugin#serialize-javascript` that would keep the vulnerable version in the deps

build(deps-dev): bump serialize-javascript from 1.3.0 to 2.1.2

---

test/unit/modules/vdom/patch/element.spec.js

chore: fix typo in element test

---

README.md

Add `?sanitize=true` to svg. But maybe it’s better to replace it to png?
Link to the similar issue: https://github.com/github/markup/issues/556

fix(readme): svg doesnt displayed 

---

dist/README.md

This PR fixs the sample code for Webpack configuration, following the note in the [define-plugin#usage](https://webpack.js.org/plugins/define-plugin/#usage) documention:
> When defining values for process prefer 'process.env.NODE_ENV': JSON.stringify('production') over process: { env: { NODE_ENV: JSON.stringify('production') } }. Using the latter will overwrite the process object which can break compatibility with some modules that expect other values on the process object to be defined.

dist/README.md : small Webpack sample code fix

---

flow/weex.js
src/compiler/parser/index.js
test/unit/features/directives/on.spec.js
types/umd.d.ts

This is a drive-by contribution, and I had trouble testing on my host.  When I ran npm test, everything succeeded/passed until attempting to start a webserver, since I already have something listening on port 8080 that I didn't want to shut down.  I tried _npm test --port 8111, which looked like it was going to work, but there are a bunch of hard-coded instances of :8080 under e2e/specs that I think are the cause.  I'll open a separate issue for that.

chore: spelling and grammar. fix #11480

---

package.json
packages/vue-server-renderer/package.json
yarn.lock

Security update from https://github.com/vuejs/vue/issues/11427 and https://app.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-570062
Breaking changes listed at https://github.com/yahoo/serialize-javascript/releases

chore: upgrade serialize-javascript

---

src/core/vdom/create-component.js

Fix #10843
Since it's not supported on [many browsers](https://caniuse.com/#feat=mdn-javascript_grammar_trailing_commas_trailing_commas_in_functions), we should just remove it

fix(core): remove trailing comma in function signature

---

src/server/template-renderer/create-async-file-mapper.js

> Reproduction: https://github.com/LoveofRedMoon/vue-ts-ssr-demo.git
when i run 'npm run build:win' (actually file `vue-ssr-client-manifest.json =&gt; modules =&gt; any` contains -1)
then 'ts-node serve/serve.ts',&nbsp; the serve starts.
when visit any web (ex: localhost:8000), it will shows error 'Cannot read property 'replaceAll' of undefined'

fix(ssr): avoid missing files in manifest

---

src/core/util/props.js
test/unit/features/options/props.spec.js

fix(props): correctly warn when a provided prop is Symbol

---

src/compiler/parser/html-parser.js
test/unit/modules/compiler/parser.spec.js

fixed #9781.
code explain:
``` javascript
const before = /^\s*((?:v-[\w-]+:|@|:|#)\[[^=]+\][^\s"'<>\/=]*)(?:\s*(=)\s*(?:"([^"]*)"+|'([^']*)'+|([^\s"'=<>`]+)))?/;
const after = /^\s*((?:v-[\w-]+:|@|:|#)\[[^=]+?\][^\s"'<>\/=]*)(?:\s*(=)\s*(?:"([^"]*)"+|'([^']*)'+|([^\s"'=<>`]+)))?/;
let s = ' #[foo]>foo</template><template #[bar]>bar</template>';
let beforeMatch = s.match(before);
let afterMatch = s.match(after);
console.log(beforeMatch[0]);     // …
```

fix(parser): fixed `dynamicArgAttribute` RegExp

---

types/options.d.ts
types/test/options-test.ts

Adds missing TypeScript type info allowing watcher handler to be of `string` type

fix(types): allow string for watch handlers

---

src/compiler/codegen/events.js
test/unit/modules/compiler/codegen.spec.js

Pass full parent argument list to the event handler when there are event
modifiers present.
Fix #10867

fix(compiler): event handler with modifiers swallowing arguments

---

src/platforms/web/util/attrs.js

When present, translate attribute had translate as it's value, which is not valid, the value should
remain as specified by the user, that's why we removed it form isBooleanAttr map
fix #11391

fix #11391: translate attribute had incorrectly the key as it's value

---

src/platforms/web/runtime/modules/attrs.js
test/unit/features/directives/pre.spec.js

Fix #10087
When attributes under a v-pre match the list in `isBooleanAttr`, the value is replaced. This goes against the purpose of v-pre which is to leave all elements as-is.
An example of this bug can be found at https://jsfiddle.net/fp1omdaw/1/ as well as further details under #10087

fix(v-pre): do not alter attributes (fix #10087)

---

README.md

URLs updated to use HTTPS protocol where appropriate to improve security and privacy.
- [X ] Other, please describe:
URLs updated to use HTTPS protocol where appropriate to improve security and privacy.
- [ X ] No

chore: update HTTP -> HTTPS

---

src/core/vdom/create-element.js
test/unit/features/directives/on.spec.js

Removes confusing warning
Fix #10939

feat(warns): avoid warning native modifiers on dynamic components

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

The regex for whitespace was too strict and was causing $nbps; chars to
disappear from templates when `whitespace: 'condense'` is set. Changing the rule
to avoid converting non-breaking white space chars into regular spaces.
Fixes #10485
Fixes #11059

fix(compiler): avoid converting &nbps; to spaces

---

src/core/util/props.js

After looking at the performance of one of my apps, I noticed, the function, that took the most time summed up was `getType()` , defined in [1] taking 200ms. I noticed the regular expression getting created for each call and measured again including the proposed improvement, which took the time down to 150ms. To make sure I changed it back to confirm and it again timed at 200ms.
[1]
https://github.com/vuejs/vue/blob/b07087deae060244fe5d9651b38dc5f1e79667a9/src/core …

perf: preinitialize typeCheck RegExp

---

types/test/options-test.ts
types/vnode.d.ts

I changed expression type  to optional string
fix #10871
it seems stopped since December ... so i try it 🙌
please point out if i have any deficiencies 🙏

fix(types): changed expression type to optional string

---

src/core/util/props.js
test/unit/features/options/props.spec.js

Closes #9224
**Before**
**After**

fix(warn): better message with no constructors props

---

src/core/util/props.js
test/unit/features/options/props.spec.js

Just a simple addition to make BigInt validation work.
Close #11126

fix(props): support BigInt in props type validation

---

src/compiler/codegen/index.js
test/unit/features/component/component.spec.js

- [ x ] Bugfix
- [ x ] No
- [ x ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ x ] New/updated tests are included
Root level <script> tags should not be …

fix(vdom): avoid executing root level script tags

---

src/core/instance/state.js
test/unit/features/instance/methods-lifecycle.spec.js

fix: pause dep collection during immediate watcher invocation

---

src/platforms/web/server/modules/attrs.js
test/ssr/ssr-string.spec.js

Fix [11297](https://github.com/vuejs/vue/issues/11297).
After this fix inheritAttrs option works in a correct way and don't add attributes to html output.

fix(ssr): inheritAttrs false adds attributes to html

---

src/platforms/web/util/element.js

fix: give correct namespace in foreignObject

---

src/compiler/parser/index.js
test/unit/modules/compiler/parser.spec.js

Add condition to see whether the element may be an component.
fixes #10152

fix(warns): modify `maybeComponent` function in parser

---

src/core/vdom/helpers/normalize-scoped-slots.js

**Context:**
- Reproduction: https://replit.com/@pi0/vuejsvue10391
- resolves #10391, resolves nuxt/nuxt.js#8904. resolves nuxt/components#164

fix: handle async placeholders in normalizeScopedSlot 

---

src/compiler/codegen/index.js
src/core/instance/render-helpers/render-slot.js
test/unit/features/component/component-slot.spec.js
test/unit/modules/compiler/codegen.spec.js

slot fallback content should be evaluated only when the parent is not providing it.
fixes #10224

fix(slot): add a function to return the slot fallback content

---

src/core/instance/render-helpers/check-keycodes.js
test/unit/features/directives/on.spec.js

Chromium browsers (and Safari) trigger a `keydown`/`keyup` event on autocomplete. An `Event` object without `key` or `keyCode` is generated.
Vue, when listening with modifiers, is triggering the callback even if the modifier key doesn't match the `undefined` keyCode of the event.
Current behaviour: https://codepen.io/zupolgec/pen/RwWRxdK
New behaviour: https://codepen.io/zupolgec/pen/qBONxMj
Try autocompleting the first field: in the first demo is counted, in the second demo is ignored.
See also same kind of issue on another JS library: https://github.com/alpinejs/alpine/pull/389#issuecomment-615935688

fix(v-on): avoid events with empty keyCode (autocomplete)

---

src/core/instance/state.js
test/unit/features/options/computed.spec.js

feat(warn): warn computed conflict with methods

---

src/core/vdom/patch.js
test/unit/modules/vdom/patch/edge-cases.spec.js

I found and fixed a vdom bug related to async component and SSR.
I originally noticed this bug on my closed project using Nuxt.
The minimal reproduction code is included in test.
Throw when hydrated pending async component is patched by v-if="false" node.
(version: 2.6.11)
1. v-if="false" node is represented by comment node
2. sameVNode returns true when asyncPlaceholder and comment are compared.
3. patchVNode executed for asyncPlaceholder and comment.
4. comment doesn't have asyncFactory but asyncFactory.resolved is accessed.
Fix sameVNode to return false when asyncPlaceholder and comment are compared.
If yes, please describe the impact and migration path for …

fix(core): fix sameVnode for async component

---

types/vue.d.ts

Added undefined as a return type of $refs as it was quite hard to convince typescript that something COULD be undefined if you type in a ref that doesn't exist,
I also changed the two array statements from `Element[] | Vue[]` to `(Element | Vue)[]` because it's not guaranteed that they are ALL Elements or they are ALL Vue components. (Very likely, yes, but not always)
For example
```html
<template v-for="(a, index) of b">
<div v-if="index % 2 === 0" ref="test"></div>
<my-component v-else ref="test"></my-component>
</template>
```
If adding a …

fix(types): make $refs undefined possible

---

src/core/components/keep-alive.js
test/unit/features/component/component-keep-alive.spec.js

fixes #9842
Fixes https://github.com/vuejs/vue-router/issues/2549
Fixes #9972

fix(keep-alive): cache what is really needed not the whole VNode data

---

src/core/vdom/helpers/normalize-scoped-slots.js
test/unit/features/component/component-slot.spec.js

fix(v-slot): fix scoped slot normalization combined with v-if

---

packages/vue-server-renderer/package.json
src/server/webpack-plugin/client.js
src/server/webpack-plugin/server.js
src/server/webpack-plugin/util.js

Similar to #11863, but:
- Fix modules mapping in client plugin
- Ignore hmr assets
- Fix the deprecation warning
Fix #11718
Close #11863

feat(ssr): vue-ssr-webpack-plugin compatible with webpack 5

---

types/options.d.ts
types/test/async-component-test.ts

Look at this codeexample:
```ts
import { AsyncComponent, Component } from 'vue'
const a: AsyncComponent = () => ({
component: new Promise<Component>((res, rej) => {
res({})
}),
})
const b: AsyncComponent = () => ({
component: () =>
new Promise<Component>((res, rej) => {
res({})
}),
})
```
The first example is like in the docs https://vuejs.org/v2/guide/components-dynamic-async.html#Handling-Loading-State and the second example should not work (I also looked at the implementation and I think this would not work).
The types …

fix(types): async Component types

---

src/platforms/web/runtime/modules/events.js
test/unit/features/component/component-keep-alive.spec.js

Add removing all dom event listeners when vnode destroyed
fixes #10083
fixes #10004 

fix(v-on): add removing all dom event listeners when vnode destroyed

---

src/platforms/web/compiler/modules/class.js
test/ssr/ssr-string.spec.js
test/unit/features/directives/class.spec.js

Template "static" classes used to preserve whitespace after compilation, resulting in builds that had bigger file outputs with whitespace in component's `staticClass` attributes, as specified in #12113 and [this issue](https://github.com/prettier/prettier/issues/10918#issuecomment-854023245) as well.
fix #12113

feat(compiler): condenses staticClass whitespace (fix #12113)

---

.git-blame-ignore-revs

See https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
Ideally, all style-only-commits should be put on this list.
The "move to typescript" is not trivial by itself, but most of the
additions/deletions are style changes. So I think it's safe and more
reader-friendly to exclude it.
Blame view before the PR:
https://github.com/vuejs/vue/blame/v2.7.0-alpha.4/src/platforms/web/runtime/transition-util.ts
After the PR:
https://github.com/sodatea/vue/blame/chore-better-git-blame/src/platforms/web/runtime/transition-util.ts …

chore: exclude trivial refactors from `git blame` results

---

benchmarks/ssr/renderToStream.js
benchmarks/ssr/renderToString.js

chore(benchmarks:ssr): require createRenderer function path error

---

packages/compiler-sfc/src/templateCompilerModules/srcset.ts

The `substr` is deprecated. 
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

chore(compiler-sfc): replace `substr` with `slice`

---

packages/compiler-sfc/src/compileScript.ts
src/core/vdom/modules/directives.ts
types/vnode.d.ts

Components can be rendered without registering them in options.components:
```js
Vue.extend({
render (h) {
return h(MyComponent)
}
})
```
But directives can't:
```js
Vue.extend({
directives: { MyDirective },
render (h) {
return h(MyComponent, {
directives: [{ name: 'my-directive' }]
})
}
})
```
This change allows you to do:
```js
Vue.extend({
render (h) {
return h(MyComponent, {
directives: [{ def: MyDirective }]
})
}
})
```
This already mostly works in 2.7 beta, but there is no type definition and it is overwritten in `<script setup>` components
---

feat: allow passing directive definition directly to h()

---

src/shared/constants.ts

Hi, the `renderTracked` and `renderTriggered` hooks almost work (Options API) but it looks like a merge strategy was never added. `callHook` expects `$options[hook]` to be an array
Here is a demo: https://jsfiddle.net/qvmz2dps/
Thought it was straightforward enough not to add tests, but I can do so

fix(hooks): add renderTracked/Triggered merge strategy

---

examples/todomvc/app.js
packages/vue-server-renderer/build.dev.js
packages/vue-template-compiler/browser.js
packages/weex-template-compiler/build.js
packages/weex-vue-framework/factory.js
src/compiler/codegen/index.js
src/core/instance/proxy.js
src/core/instance/state.js
src/platforms/web/runtime/index.js

Some links currently are broken like:
- https://vuejs.org/guide/computed.html (should be https://v2.vuejs.org/v2/guide/computed.html)
- https://vuejs.org/guide/list.html#key (should be https://v2.vuejs.org/v2/guide/list.html#Maintaining-State)
Some links still working. However, for consistency, I also updated them as well.
Thanks.

Fix some URLs in warn messages which link to v2 doc site

---

CHANGELOG.md

chore(changelog): fix dead link

---

dist/vue.runtime.mjs

`onBeforeUnmount` was omitted in `dist/vue.runtime.mjs` - see https://github.com/vuejs/vue/issues/12626#issuecomment-1179171109
resolves https://github.com/nuxt/bridge/issues/393

fix: add missing export (`onBeforeUnmount`) from `vue.runtime.mjs`

---

types/vue.d.ts

`$refs` in Vue's previous instance can also contain references to the new `defineComponent` style components. This fixes an issue where if you are referencing a `defineComponent` component inside a `vue-class-component` it throws errors about mismatching `$refs` type

$refs can also contain CreateComponentPublicInstance

---

packages/compiler-sfc/package.json
packages/compiler-sfc/src/compileTemplate.ts
pnpm-lock.yaml
test/unit/features/options/functional.spec.ts

chore(compiler-sfc): remove useless vue-template-es2015-compiler

---

src/compiler/codegen/index.ts

fix(codegen): improve resolve component name in <script setup>

---

types/vue.d.ts

This PR makes the `SetupBindings` parameter optional on types `ExtendedVue` and `CombinedVueInstance`.
See 
- https://github.com/vuejs/vue/issues/12726
- https://github.com/vuejs/vue/issues/12717
Steps to repro:
```
git clone git@github.com:jf-paradis/demo-vue-issues.git
cd demo-vue-issues
npm install
npm run test
```

fix(types): Make SetupBindings optional (fix #12726, #12717)

---

packages/compiler-sfc/src/templateCompilerModules/utils.ts

fix #12731
modeled after https://github.com/vuejs/core/blob/a95554d35c65e5bfd0bf9d1c5b908ae789345a6d/packages/compiler-sfc/src/templateTransformAssetUrl.ts#L120-L130

fix: allow full hostnames in asset url base, fix #12731

---

types/options.d.ts
types/test/vue-test.ts
types/v3-component-public-instance.d.ts
types/vue.d.ts

Type inference improvements, close #12730

feat(types): new Vue() improvements (#12730)

---

src/core/vdom/modules/directives.ts
test/unit/features/v3/apiSetup.spec.ts

Fix #12743
If I miss anything, please comment to remind me. :)

fix: directives shorthand normalize error (fix #12743)

---

src/v3/apiLifecycle.ts

chore(v3/lifecycle): Enhanced type for onErrorCaptured

---

packages/server-renderer/src/render.ts
packages/server-renderer/test/ssr-string.spec.ts
src/core/vdom/vnode.ts

This is a follow-up of https://github.com/vuejs/vue/pull/11287 which resolves #10733.

fix(src/server/render.js): fixes component directives rendering (fix #10733)

---

types/options.d.ts
types/vue.d.ts

related vue 3 code:
https://github.com/vuejs/core/blob/8772a01a9280b1591e781e20741d32e2f9a836c8/packages/runtime-core/src/apiCreateApp.ts#L36
fix https://github.com/vuejs/vue/issues/12791

fix(types): vue 3 directive type compatibility

---

src/core/observer/index.ts

fix [#12812](https://github.com/vuejs/vue/issues/12812)

fix(12812): skip the component while creating observer

---

types/jsx.d.ts

Set style attribute on svg to use `StyleValue`

fix(types): style attribute svg

---

examples/classic/elastic-header/index.html
examples/classic/todomvc/app.js
examples/classic/todomvc/readme.md
src/compiler/codegen/index.ts

https://github.com/vuejs/vue/pull/12653 (to the `dev` branch)
https://github.com/vuejs/vue/pull/12725

chore: fix some broken links to v2 docs

---

types/jsx.d.ts

Closes #12832 
Be related to Vue3 [#6855](https://github.com/vuejs/core/pull/6855)

fix(types): stricter type condition for `EventHandlers`

---

types/test/vue-test.ts
types/vnode.d.ts

fix(types):fix Spreading data functional components TSX type error (fix #12778)

---

packages/compiler-sfc/src/compileScript.ts
packages/compiler-sfc/test/compileScript.spec.ts
src/compiler/parser/index.ts

fix(compiler-sfc): fix template usage check edge case for v-slot destructured default value (#12841)

fix(compiler-sfc): fix template usage check edge case for v-slot destructured default value (#12841)

---

src/core/observer/index.ts

chore: fix typo

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
examples/classic/todomvc/index.html
examples/classic/todomvc/readme.md
src/compiler/parser/html-parser.ts
src/platforms/web/util/element.ts

chore: update links (http=https)

---

src/core/instance/lifecycle.ts
test/unit/features/v3/reactivity/effectScope.spec.ts

This pull request's issue originates from a specific problem mentioned in https://github.com/vuejs/pinia/issues/1800 . Due to the potential for callHook to modify the upper-level scope's behavior of collecting effects, it subsequently leads to incorrect effects being torn down when stopping in the wrong scope.

fix(lifecycle): scope might changed when call hook

---

types/options.d.ts

fix(types): serverPrefetch's this type doesn't include component properties 

---

packages/compiler-sfc/src/compileScript.ts
packages/compiler-sfc/test/__snapshots__/compileScript.spec.ts.snap
packages/compiler-sfc/test/compileScript.spec.ts

fix(compiler-sfc): fix macro usage in multi-variable declaration

---

packages/compiler-sfc/src/compileScript.ts
packages/compiler-sfc/test/__snapshots__/compileScript.spec.ts.snap

fix(compiler-sfc): add semicolon after `defineProps` statement

---

src/core/vdom/patch.ts
test/unit/modules/vdom/patch/edge-cases.spec.ts

repro: https://jsbin.com/zobarureye/edit?html,js,console,output
There is a component called `v-switch` that is placed inside a `transition-group` element. The `v-switch` component has a directive called `v-foo`, accepts a boolean prop called `isOn` and switches its template root according to the value of `isOn`. The `v-foo` directive has an inserted hook that should be called to ensure that the binding logic is refreshed whenever the template root changes.

fix(patch): clone insert hooks to avoid being mutated during iteration

---

packages/compiler-sfc/package.json
pnpm-lock.yaml

close: #13052
`@vue/compiler-sfc` optionally uses Prettier and it is not compatible with Prettier v3.
But `prettier` is not listed in the `package.json`.
It wasn't a problem with Prettier v2 because prettier is [optional dependency of `component-compiler-utils`](https://github.com/vuejs/component-compiler-utils/blob/82a37174990e31eaec609887a0ec262f06b454dd/package.json#L69). So Prettier is installed anyway and everything works.
But if some project has …

chore(compiler-sfc): specify prettier version (fix #13052)

---

package.json

Each commit contains a pretty lengthy description to try to make things as clear as possible. Rather than reproduce that here, the short version is that this PR contains two bug fixes:
1) Fixes #13106 which deals with type augmentation being broken in the ecosystem when enabling the "moduleResolution": "bundler" typescript option. This is due to the export map requiring full filenames with extensions, even though they are almost never provided as such
2) Fixes an …

fix: type augmentation and compiler-sfc types w/moduleResolution: bundler (fix #13106)

---

src/v3/reactivity/ref.ts
types/test/v3/reactivity-test.ts
types/test/v3/watch-test.ts

fix#12978 shallowRef's return type 

---

README.md

Updated Browser Compatibility reference. The previous currently returns HTTP 404.
Updated browser compatibility reference for ES5. The previous currently returns HTTP 404.

Update README.md (browser compatibility reference)
