src/compiler/transclude.js
test/unit/specs/compiler/transclude_spec.js

<content> select should only match children.

---

src/transition/css.js

Prevent unused variable warning from all linters

---

CONTRIBUTING.md

Just a tiny typo fix on contribution guidelines from last Friday night

Minor typo fix

---

src/directives/attr.js

Fix missed braces for https://github.com/yyx990803/vue/pull/902.

Fix braces

---

src/util/lang.js
src/watcher.js

Update: lang/isObject must return {Boolen}; lang/isArray more faster now

---

gruntfile.js

use a simpler CI build for pull requests

---

src/filters/index.js
test/unit/specs/filters/filters_spec.js

This is a continuation of https://github.com/yyx990803/vue/pull/1140

Debounce filter & tests

---

src/filters/index.js

Added [space] key filter, i think [space] is important and frequent

Added [space] key filter

---

src/directives/public/bind.js

Fixing a spelling error, nothing crazy.

Fixing spelling error of the word ‘attribute’

---

src/util/dom.js

fix typo of by

---

src/directive.js
test/unit/specs/directive_spec.js

dynamic attribute don't work on custom directive.
please see the following jsfiddle:
https://jsfiddle.net/kazupon/of17drkk/6/

fix dynamic attribute on custom directive

---

package.json

the description had a typo in the word "interactive"

fixed a typo in package.json

---

src/directives/public/on.js
test/unit/specs/directives/public/on_spec.js

1. 增加字母键别名支持，考虑到很多网站需要响应字母键，比如知乎就支持 Vim 快捷键。
2. 优化效率，判断第一个字符是不是数字，是就按照键代码解析，不是再判断字母或其他别名。
P.S. 英文好差，就打中文了（逃

Added letter keys filter

---

src/observer/index.js
test/unit/specs/directives/public/for/for_spec.js

Added test case in the for directive spec; which is where I originally ran into this issue. This test might be better moved somewhere else, but I was unclear where would be better.

Fixed bug when calling defineReactive on non-existent field with convertAllProperties on

---

src/fragment/fragment.js

Fixes: __vfrag__ references prevent GC of Vue objects 

---

src/instance/internal/lifecycle.js

removed unnecessary return value in Vue#_compile(el)

---

test/unit/specs/directives/public/for/for_spec.js

Prevent error like #2573 from happening again.

Test priorities.

---

src/compiler/compile-props.js
test/unit/specs/directives/internal/prop_spec.js

feature: allow component prop type to be an array of types

---

src/filters/array-filters.js
test/unit/specs/filters/filters_spec.js

Hello,
This feature was asked in #2518. The point of this generic filter is to support any kind of sorting by using a custom comparator. Tell me your thoughts on the feature and the code :smile: 
PS: I did the PR instead of the issue because it took little to no time to do it and I didn't have internet when I coded it :stuck_out_tongue:

orderBy can take a Function as its first argument

---

src/compiler/compile-props.js
test/unit/specs/directives/internal/prop_spec.js

Proposed fix for https://github.com/vuejs/vue/issues/2606

Default a prop before coercion

---

src/directives/public/on.js

this line may be too long
don't know if you have any 80 max-len lint rules

fix key modifier filter #2658

---

src/directives/internal/style.js
test/unit/specs/directives/internal/style_spec.js

Proposed fix for https://github.com/vuejs/vue/issues/2654

Test non-prefixed attributes before prefixed

---

src/compiler/compile.js

Fixed the fragment instance link in the console warning

---

examples/select2/index.html

Adding a default font style to match with other examples, for example (no pun intended) "Commits."

Add a default font style

---

src/compiler/parser/html-parser.js
src/compiler/parser/text-parser.js
src/core/global-api/extend.js
src/core/global-api/use.js
src/core/instance/events.js
src/core/instance/lifecycle.js
src/core/instance/state.js
src/core/observer/array.js
src/core/observer/batcher.js
src/core/observer/dep.js
src/core/observer/index.js
src/core/observer/watcher.js
src/core/util/debug.js
src/core/util/env.js
src/core/util/lang.js
src/core/util/options.js
src/core/util/props.js
src/core/vdom/create-component.js
src/core/vdom/patch.js
src/entries/web-runtime-with-compiler.js
src/platforms/web/runtime/class-util.js
src/platforms/web/runtime/modules/style.js
src/platforms/web/util/class.js
src/platforms/web/util/index.js
src/server/render-stream.js
src/shared/util.js

I guess 2.0 is a perfect opportunity to adapt ES6 fully. Using `const` and `let` instead of `var` is a good start.

Replace var with proper let/const

---

src/util/options.js
test/unit/specs/util/options_spec.js

The extends option supports an extended constructor

---

src/compiler/codegen.js
src/core/instance/state.js
src/entries/web-runtime.js
src/shared/util.js

Currently the `noop` function is being declared and used randomly at places. This commit moduralizes it (_à la_ lodash) for more DRY code.

[2.0] Moduralize the noop() function

---

package.json
test/unit/specs/util/dom_spec.js

In `dev` branch, I upgrade eslint and fixed eslint error because eslint is too old.

Fix eslint error

---

test/unit/modules/observer/observer.spec.js

NOTE: bring vue 1.x observer test

add observer tests

---

test/unit/modules/compiler/optimizer.spec.js

add optimizer tests

---

benchmarks/ssr/README.md
benchmarks/ssr/common.js
benchmarks/ssr/renderToStream.js
benchmarks/ssr/renderToString.js
package.json

- Includes `renderToStream` and`renderToString`
- Added SSR benchmark README.md
- Renders table with 10000 rows with 100 columns (1 million cells)

Added benchmark for SSR

---

src/filters/index.js
test/unit/specs/filters/filters_spec.js

Fix json filter call with 0 as a parameter

---

test/unit/modules/compiler/codegen.spec.js

ref #2872
I think that is not the best about codegen checking because it is hard coding.
Are there any good idea ?
I think that there are following about codegen checking:
- helper method for codegen test (e.g. genElement)

add codegen tests

---

test/unit/modules/vdom/create-component.spec.js

add create-component tests

---

test/unit/features/directives/style.spec.js

Unit tests for v-bind:style

---

test/unit/modules/vdom/create-element.spec.js

add create-element tests

---

test/unit/features/options/mixins.spec.js
test/unit/features/options/name.spec.js
test/unit/features/options/parent.spec.js

tests for parent, name and mixins

---

src/entries/web-runtime.js
src/platforms/web/runtime/patch.js
test/helpers/vdom.js
test/unit/.eslintrc
test/unit/index.js
test/unit/modules/vdom/modules/attrs.spec.js
test/unit/modules/vdom/modules/class.spec.js
test/unit/modules/vdom/modules/directive.spec.js
test/unit/modules/vdom/modules/events.spec.js
test/unit/modules/vdom/modules/props.js
test/unit/modules/vdom/modules/style.spec.js
test/unit/modules/vdom/modules/transition.spec.js
test/unit/modules/vdom/patch/children.spec.js
test/unit/modules/vdom/patch/element.spec.js
test/unit/modules/vdom/patch/hooks.spec.js
test/unit/modules/vdom/patch/hydration.spec.js

add patch tests

---

src/entries/web-runtime-with-compiler.js
test/unit/features/options/template.spec.js

add options template tests

---

test/unit/features/options/el.spec.js

add options el tests

---

test/unit/features/options/render.spec.js

add options render tests

---

src/compiler/directives/ref.js

Break in loop when condition is fulfilled.

Added the missing break

---

test/ssr/ssr-string.spec.js

add ssr custom directive test

---

src/directives/internal/transition.js

Since always remove the old class.

remove a needless if.

---

src/global-api.js
test/unit/specs/global_api_spec.js

fix 'name' option issue

---

examples/select2/index.html

Otherwise it doesn't work if the page is loaded with http.

Load external assets with https in select2 example

---

src/core/instance/init.js

Should fix https://github.com/vuejs/vue/issues/3054

Fix options for inline-template instances

---

backers.md

Sorry, my name got cut off on my Pateron profile

---

backers.md

My name is Nikola not "Nokola" :) Keep up the good work ;)

Fix misspelled backer (Nikola Trifunovic)

---

src/platforms/web/runtime/directives/model.js
test/unit/features/directives/model-component.spec.js

Reproduction example
https://jsfiddle.net/kazupon/h5mvxq82/6/

Fix v-model warning on component

---

types/index.d.ts
types/options.d.ts
types/plugin.d.ts
types/test/options-test.ts
types/test/plugin-test.ts
types/test/vue-test.ts
types/vnode.d.ts
types/vue.d.ts

remove ".d" from paths in definition files

---

types/options.d.ts
types/test/options-test.ts

A type of a new directive hook from 2.0-rc.5

Add inserted hook type to directive option

---

src/util/lang.js

camelize comment typo (#3696)

---

test/unit/modules/vdom/patch/children.spec.js

Optimization unit testing in` vdom/patch/children.spec.js `

Optimization unit testing

---

src/parsers/directive.js
test/unit/specs/parsers/directive_spec.js

Use a state machine based expression parser to parse the directive.
fix #3210 and #3214 #

use a simple expression parser instead of regexp to parse directive

---

src/platforms/web/runtime/directives/model.js

Fix for https://github.com/vuejs/vue/issues/3798

fix IE/Edge select remembering selection

---

README.md

Fix reference to backers.md

---

src/core/util/env.js
src/server/write.js

setTimeout fallback update 

---

src/core/observer/index.js

fixed #3942

---

src/core/vdom/vnode.js

Fix typo in 'component'

---

src/platforms/web/util/attrs.js

Inline export for consistency

---

src/compiler/codegen/index.js
src/core/observer/watcher.js

Thank you for great library!
This PR includes only small improvements.

Small performance improvement in watcher.js

---

src/directives/public/on.js
test/unit/specs/directives/public/on_spec.js

add ctrl, shift and alt modifiers for v-on

Modifiers key modifier for directive on

---

types/options.d.ts
types/test/options-test.ts

fix RenderContext

---

types/vue.d.ts

remove ".d" from paths

---

src/util/lang.js

Backport the behavior from vue2.
fix #3577 #3541 . Maybe a breaking fix as discused.

[1.x]Empty string should not be casted to 0 (fix #3577, #3541)

---

src/platforms/web/server/modules/class.js
test/ssr/ssr-string.spec.js

Update ssr class render (fix #4143)

---

packages/weex-template-compiler/README.md
packages/weex-template-compiler/package.json
packages/weex-vue-framework/README.md
packages/weex-vue-framework/package.json

fixed deps and README for the 2 packages about weex

---

src/compiler/helpers.js
test/unit/features/directives/model-parse.spec.js

fix object dot notation bug (fix #4185)

---

test/unit/features/directives/style.spec.js

destroyed elements pass their styles onto others that are similar

---

src/platforms/weex/compiler/modules/append.js

weex: set append="tree" by default for <cell> component

---

src/platforms/web/util/style.js
test/unit/features/directives/static-style-parser.spec.js

fix #4346 
Remove the unproper hasBackground check and add more test cases.

fix static style parse error (fix #4346)

---

dist/README.md

Fix unkpg.com -> unpkg.com

---

test/unit/features/directives/model-checkbox.spec.js
test/unit/features/directives/model-radio.spec.js
test/unit/features/directives/model-select.spec.js

Related to PR #4528  . Add boolean type test case

Improve looseequal test case

---

test/unit/features/component/component.spec.js

add unit test for dynamic component with props

add unit test for dynamic component with props

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

For SSR issue, it's better to recommend the user to privide reproduction repository.

Recommend user to provide reproduction repository for ssr issue

---

build/karma.cover.config.js

As a bit something, I found a consistency disagreement in the comment. 😉

tweak comment of coverage setting

---

src/compiler/parser/text-parser.js

fix #4344 #4445 #4511

---

test/unit/features/directives/model-checkbox.spec.js

fix checkbox test case

---

src/transition/transition.js

Fix hot reload in IE in strict mode

---

src/core/vdom/helpers/normalize-children.js

[Documentation] fixed typo on line 15

---

packages/vue-template-compiler/README.md

ref: CompiledResult type at https://github.com/vuejs/vue/blob/dev/flow/compiler.js#L23

docs(packages/vue-template-compiler): add compiler result field

---

src/compiler/parser/html-parser.js

small improvements on html-parser

---

flow/component.js
src/core/instance/lifecycle.js
src/core/vdom/modules/ref.js
src/core/vdom/patch.js
test/unit/features/ref.spec.js

Changes proposed in this pull request:
- Add ref callback
/ping @yyx990803

[WIP] Support for ref callback

---

src/core/instance/state.js

fix doc comment typo

---

src/compiler/parser/index.js

remove unnecessary code

---

package.json

Add missed vue.esm.js and vue.runtime.esm.js to files section package.json

Add esm-files to package.json

---

src/core/util/error.js

NOTE:
related docs: https://github.com/vuejs/vuejs.org/pull/787
adjust to flowtype definition
https://github.com/vuejs/vue/blob/dev/src/core/config.js#L12

refactor argument name

---

examples/todomvc/app.js

chore: check binding.value instead of just binding object

---

src/compiler/error-detector.js
test/unit/features/options/template.spec.js

Fix: https://github.com/vuejs/vue/issues/4966

imporve:check the delete oparator in event expression

---

test/unit/features/component/component-slot.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore: preserveWhitespace is true by default

---

test/unit/features/component/component-slot.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore: fix some closetag mismatches

---

test/unit/features/directives/once.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(once.spec): \s match all whitespaces

---

test/unit/features/directives/model-text.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(model-text.spec): add a missing check

---

test/unit/features/filter/filter.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(filter.spec): fix variable-- test case

---

test/unit/features/directives/model-select.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore(model-select.spec): add a check for value binding and fix some typo

---

test/unit/modules/compiler/parser.spec.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This is unconfirmed, since I don't have IE at the moment.

chore(parser.spec): fix an IE conditional test with a typo

---

.github/PULL_REQUEST_TEMPLATE.md

_Using the updated PR template below - so meta!_
- Improved consistency of language in the template
- Reorganized template a little
- Added instructions at the top for how to check boxes

Reorganize and update PR template

---

src/core/observer/scheduler.js
test/unit/modules/observer/scheduler.spec.js

fix no change triggered after reassigned state, Fix #5191

---

src/core/vdom/create-component.js

fix a typo

---

src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-checkbox.spec.js

Use genAssignmentCode in chehckbox model web compiler

---

src/platforms/web/runtime/directives/model.js

fix a typo in comment

---

README.md

fixed readme for styling inconsistencies

---

README.md

Fix 0 download issue with monthly download shield

---

src/core/vdom/patch.js

Add the declaration of the local variable `i` in` removeAndInvokeRemoveHook`

improve:add local variable declaration

---

packages/vue-server-renderer/README.md
packages/vue-template-compiler/README.md
packages/weex-template-compiler/README.md
packages/weex-vue-framework/README.md

Broken links make people 😢.
This PR updates the readme links for the generated packages. I guess the README's are not generated but couldn't find out for sure.
I was unsure where to link because the structure changed a little, I went with what made the most sense to me.
Vue is ✨. You are ✨. Have a great day!

Update packages readme links

---

src/core/util/env.js

tweak type definition layouting

---

src/core/observer/scheduler.js

improve: optimize the performance of scheduler

---

src/compiler/codegen/events.js
src/compiler/codegen/index.js
src/compiler/parser/html-parser.js
src/compiler/parser/index.js
src/core/instance/index.js
src/core/instance/render-helpers/resolve-slots.js
src/core/util/props.js
src/core/vdom/create-element.js
src/core/vdom/patch.js
src/platforms/web/runtime/components/transition.js
src/platforms/web/runtime/index.js
src/platforms/web/runtime/modules/style.js
src/platforms/web/runtime/modules/transition.js
src/platforms/web/runtime/transition-util.js
src/platforms/web/server/modules/dom-props.js
src/platforms/weex/runtime/modules/class.js
src/platforms/weex/runtime/modules/transition.js
src/server/render.js

Currently there are two code styles in the repository, this PR updates the related codes to the first one.
```js
if (tester1 &&
tester2 &&
tester3
) {
// code
}
```
and
```js
if (tester1 &&
tester2 &&
tester3) {
// code
}
```

[Code style update] improve mutli-line `&&` code style to keep consistence

---

test/unit/features/component/component-scoped-slot.spec.js

Add the test case where v-for scoped slot and single scoped slot used together.

[Test Case Updated] improve scoped slot test case

---

types/test/vue-test.ts
types/vue.d.ts

This PR adds the missing TypeScript definition for `this.$ssrContext`, which was added in v2.3.2.

Add TypeScript definition for ssrContext

---

packages/vue-server-renderer/README.md

fix doc link 404

---

src/compiler/codegen/index.js

del unused argument.
this argument `state` seems not be used, maybe a little confusing.

chore:del unused argument.

---

src/core/observer/scheduler.js

maintain consistency of function name

---

src/platforms/web/runtime/components/transition.js

https://github.com/vuejs/vue/pull/5796

fix:the placeholder key is undefined when render async component

---

src/platforms/web/runtime/modules/style.js

refactor: get the vendor style name in the style directive

---

src/core/observer/index.js
test/unit/features/global-api/set-delete.spec.js

https://github.com/vuejs/vue/issues/5884

Be able to use string type index in array, fix #5884

---

flow/vnode.js
src/core/instance/render-helpers/bind-object-props.js
src/core/instance/state.js
src/core/vdom/create-element.js
src/shared/util.js
test/unit/features/directives/bind.spec.js
test/unit/features/options/props.spec.js

https://github.com/vuejs/vue/issues/5881

Special attributes are invalid when using object syntax in v-bind, fix #5881

---

src/core/index.js
test/ssr/ssr-basic-renderer.spec.js

[#5941](https://github.com/vuejs/vue/issues/5941)

fix #5941, should check $vnode existence before accessing ssrContext

---

test/unit/features/global-api/set-delete.spec.js

Fix the location of the test case

test: correcting existing test case

---

src/compiler/parser/html-parser.js

remove unnecessary code.
remove 'head' tag contains 'html' tag consideration code.
I am not sure this is necessary, but all test passed after remove the code.

refactor(compile): remove unnecessary code in compile

---

src/server/template-renderer/index.js

correct variable name

---

src/core/global-api/use.js
test/unit/features/global-api/use.spec.js

support plugin with multi version vue (#5970)

---

src/core/instance/render-helpers/render-slot.js
test/unit/features/component/component-scoped-slot.spec.js

v-bind object should not override props on scopedSlots

---

src/server/bundle-renderer/create-bundle-runner.js

fix typos in src/server/bundle-renderer/create-bundle-runner.js

---

README.md

- __N/A__: New/updated tests are included

remove references to gitter; use chat.vuejs.org for discourse

---

src/compiler/codegen/index.js
test/unit/modules/compiler/codegen.spec.js

fix(compile): generate comments with special character

---

src/platforms/web/compiler/directives/model.js
test/unit/features/directives/model-checkbox.spec.js

fix: checkbox v-model="array" ignore false-value, fix #6178

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json

Update `build/release-weex.sh` and run `npm run release:weex`.

[release] weex-vue-framework@2.4.2-weex.1

---

src/core/util/env.js

`Firefox has a "watch" function...`, not `Firefix has a "watch" function...`

replace Firefix with Firefox

---

src/core/vdom/vnode.js

perf: deep clone slot vnodes on re-render

---

build/release-weex.sh
package.json
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/shared/util.js

Modify the regular to make the `replace` method call only once to optimize
performance.
This is  a performance test:  [https://jsperf.com/vue-hyphenate](https://jsperf.com/vue-hyphenate)

perf: optimize the performance of hyphenate method.

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/core/vdom/patch.js

remove repeat line in patch.js

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/core/util/env.js
types/test/plugin-test.ts
types/vue.d.ts

fix(typing): allow variadic plugin use, fix #6357

---

build/release-weex.sh
packages/weex-template-compiler/build.js
packages/weex-template-compiler/package.json
packages/weex-vue-framework/factory.js
packages/weex-vue-framework/index.js
packages/weex-vue-framework/package.json
src/compiler/parser/html-parser.js
src/core/util/env.js

Why cancel the subpattern when defining singleAttrAssign and then add subpattern when joining the strings... weather it's necessary...

singleAttrAssign regular expression subpattern

---

README.md

Fixed typo in changelog section

---

build/alias.js

chore($build): clarify alias resolution for rollup build

---

packages/vue-server-renderer/README.md
packages/vue-template-compiler/README.md
packages/weex-template-compiler/README.md
packages/weex-vue-framework/README.md

fix: update packages readme links which point to 404

---

src/core/observer/index.js

While this introduces a slight behavior change, I believe the only scenario in which this would cause breakage is if an application has a non-reactive object inside of a non-reactive array and is relying on the reactivity system to detect changes to the elements in that array. This seems incredibly unlikely to happen as that use case has already gone to lengths to opt out of reactivity in the first place, so I expect this to be nothing but a performance improvement for those use cases if they exist.
- [?] All tests are passing: …

fix #6284: avoid iterating non-observable arrays

---

packages/vue-template-compiler/README.md

improve package docs

---

src/platforms/web/runtime/components/transition.js

refactor: remove unnecessary condition

---

.github/CONTRIBUTING.md

**Other information:** Add info on types directory to CONTRIBUTING.md

docs: add types directory to CONTRIBUTING.md

---

src/core/instance/state.js
test/unit/features/options/data.spec.js

feat($core): call data method with this (#6739)

---

src/server/template-renderer/index.js

https://github.com/vuejs/vue/pull/6763#issuecomment-336370334

add semicolon before closure, fix ssr error

---

src/core/util/options.js

tweak: The value of props here is always true

---

types/vue.d.ts

Tweak definition file. Prefer user custom types over Vue builtin types for better completion item order. 

fix(types): improve typing for better completion

---

README.md

Also added Silver and Bronze sponsors.
Fixes https://github.com/opencollective/opencollective/issues/579

Fix sponsors from open collective

---

src/platforms/web/compiler/modules/model.js
test/unit/features/directives/model-dynamic.spec.js

fix #6918: v-if / v-else not working with :type + v-model

---

src/compiler/parser/index.js

minor tweak on conditions order

---

README.md

Give link for Vue examples under 'Documentation'

---

README.md

oversight, chat link was left open

docs: trivial, closing </a> after chat

---

src/server/bundle-renderer/create-bundle-runner.js

fixed windows  vue-ssr-server-bundle.json within module can't found  on server side rendering

fix windows vue-ssr-server-bundle.json within module can't found on server side rendering

---

build/release.sh

chore: fix comment typo

---

types/options.d.ts
types/vnode.d.ts
types/vue.d.ts

For more information, please check https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-and-object

fix ts types: use object and string instead of Object and String

---

src/core/util/options.js

tweak: return is better when inject has no value

---

types/vue.d.ts

refactor: extract VueConfiguration type for easy expansion (#7273)

---

test/weex/cases/recycle-list/components/editor.vue
test/weex/cases/recycle-list/components/stateful-v-model.vdom.js

fix(weex): default value for editor, fix #7165

---

README.md

Fixes https://github.com/opencollective/opencollective/issues/777

fixes gold / platinum sponsors on open collective

---

scripts/setup.js

chore: fix invalid path in setup script

---

src/core/instance/proxy.js

refactor(core): use util.isNative to remove duplicated code

---

package-lock.json
package.json
types/test/plugin-test.ts
types/test/vue-test.ts

test(types): update TS version and fix types test

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
BACKERS.md
README.md

- [ x] Other, please describe: Documentation edits for grammar and consistency (also removes some extra spaces because of linting)
- [ x] No

Edit documentation for grammar and consistency

---

src/platforms/web/runtime/directives/show.js

fix(show): prevent transitions from starting on change truthy values

---

.github/COMMIT_CONVENTION.md

docs(COMMIT_CONVENTION): update Angular's commit convention link

---

src/core/instance/inject.js

chore: modify the variable reference

---

src/platforms/web/compiler/directives/model.js

Closes #7670
I'm not sure where to test this. I was going to write a codegen test but maybe it's better to write one in `model-checkbox.spec.js`

fix(model): direct access array with multiple checkboxes

---

src/core/vdom/vnode.js

chore: fix typo

---

src/server/render-context.js

fix(ssr): add Fragment in RenderState typing

---

benchmarks/reorder-list/index.html

Reactive components count

---

flow/compiler.js

fix: no dots at the end of the comments

---

BACKERS.md

I am a bronze backer since today, just adding my info to the proper place.

Adding to backers

---

src/core/config.js
src/core/observer/dep.js
src/core/observer/scheduler.js
test/unit/features/global-api/config.spec.js
types/test/vue-test.ts
types/vue.d.ts

Closes #8200
We can use this in Vue Test Utils to run tests synchronously without editing Vue internals

Add async option

---

test/e2e/specs/todomvc.js

fix(e2e-todomvc-test): trigger click on .new-todo instead of footer, fix #7937

---

src/core/vdom/patch.js

Unsure about how to add platform-specific cases. Help needed.

fix (#8713): replace hardcoded .parentNode with abstract ops

---

README.md

it makes more sense to take the extra the out for readability.

simple grammar fix in readme. eliminated extra 'the'

---

README.md

fix(readme): correct badge link

---

examples/firebase/index.html

fix: add placeholder firebase example

---

src/server/webpack-plugin/client.js

remove useless code

---

README.md

"Vue.js is an MIT-licensed open source project. It's an independent project" --> "Vue.js is an MIT-licensed open source independent project"
"made possible entirely thanks to the support by these" --> "made possible entirely by the support of these"

Fix redundancy, structural error

---

src/core/instance/events.js

chore: update reference to already defined variable

---

src/core/observer/watcher.js
src/platforms/weex/util/element.js

empty function replace to `noop`

refactor: empty function replace to noop

---

src/compiler/parser/index.js

fix(for): use IE compatible regex in v-for regex

---

types/options.d.ts
types/test/options-test.ts

fix(types): add model option to functional components

---

src/core/instance/state.js

refactor: keep single source of truth

---

src/compiler/parser/html-parser.js

chore: remove unnecessary judgment

---

README.md

chore: update badge for Vue CLI 3

---

src/core/instance/state.js

Removed unnecessary ternary operation.

Remove redundant ternary

---

src/core/instance/render-helpers/bind-object-props.js
test/unit/features/directives/bind.spec.js

fix #8842: Override v-bind object with kebab-cased props

---

src/core/instance/render.js

Reduce the if-else nesting by coalescing two conditions.
Reduced nesting improves code's readability.
No need to add or update any test, no logic was changed.

refactor(instance render): reduce if-else nesting, coalesce conditions

---

src/core/util/next-tick.js

Make sure global state is restored in the case of an exception

---

.circleci/config.yml

See https://github.com/vuejs/regression-testing

ci: add regression test for popular libraries in Vue.js ecosystem

---

src/server/render.js

fix #8961 resolve camelCased local directives

---

test/ssr/jasmine.js
test/ssr/ssr-string.spec.js

test(ssr): add basic directives test

---

examples/todomvc/index.html

[[TodoMVC Example] [enter] key event to determin transform of Japanese characters makes the item added to list](https://github.com/vuejs/jp.vuejs.org/issues/1338)

Changing keyup to keypress to properly deal transform of Japanese chars

---

src/core/observer/dep.js

Just a minor nitpick that I ran across while perusing the source. Feel free to reject.

Minor comment cleanup

---

src/core/instance/events.js
src/core/util/debug.js
src/server/template-renderer/index.js

refactor: tiny cleanup changes

---

src/platforms/web/runtime/index.js

fix(runtime): DevTools recommendation shows for all browsers

---

src/core/observer/scheduler.js

chore: fix typo in scheduler.js

---

.github/CONTRIBUTING.md

chore: make documentation clearer

---

types/test/vue-test.ts
types/vue.d.ts

Ref: https://github.com/vuejs/vue/blob/dev/src/core/util/next-tick.js#L92
`this` in `Vue.nextTick` should always be the context.

fix(types): update this for nextTick api

---

packages/vue-template-compiler/README.md

Close: https://github.com/vuejs/vue-loader/issues/1494. 
We need to update the doc since vue-template-compiler has been removed from `vue-loader` at https://github.com/vuejs/vue-loader/commit/e32cd0e4372fcc6f13b6c307402713807516d71c

docs: clarify docs about using template compiler

---

test/unit/modules/observer/observer.spec.js

In the `observing object prop change on defined property` test case, maybe we do not need to mock a watcher which was not used.

test(observe): remove unused test code

---

scripts/alias.js

Build scripts alias for entries is not exists anymore.

chore: remove unused build alias

---

src/core/observer/scheduler.js

Technically not a bug fix, but enhances the compatibility in JSDOM.
Not sure how to test under JSDOM...

fix(core): use window.performance for compatibility in JSDOM (fix #9698)

---

packages/vue-template-compiler/index.js

This is the pull request I've created in response to the suggestion issue I submitted (#9734). In that issue, I was told there wasn't a test for this.

Template compiler warning

---

.github/CONTRIBUTING.md

Some contributors new to this project do not have `yarn` on their machines. The contributing document may confuse them when they install dependencies, so I add the instruction on how to install `yarn` if they only have `npm` installed on their machines.

docs(contributing): add instruction to install yarn

---

test/e2e/nightwatch.config.js

Can not find phantomjs binary when run e2e test on Windows. same as [PR](https://github.com/vuejs/vuex/pull/1371)

test: fix running e2e test on windows

---

src/compiler/codegen/events.js
test/unit/modules/compiler/codegen.spec.js

fix #9920: fix function expression regex

---

src/core/instance/render.js

chore(typo): fix comment typo

---

src/core/instance/proxy.js

chore: fix proxy warning typo

---

packages/vue-template-compiler/README.md

- [] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

docs: fix link to point to ModuleOptions lines

---

src/compiler/parser/index.js

chore: fix typo in <template v-slot> warning

---

src/core/util/next-tick.js

chore: fix typo in `next-tick.js` comment

---

src/platforms/web/compiler/modules/model.js

docs(compiler) fix typo

---

dist/README.md

docs: fix minor typo

---

README.md

fix(readme): svg image

---

src/core/instance/render-helpers/bind-dynamic-keys.js

chore: fix typo in `bind-dynamic-keys.js` comment

---

.editorconfig

chore: https link to editorconfig.org

---

.github/CONTRIBUTING.md

Add missing donation link via PayPal or crypto-currencies in CONTRIBUTING.md file
Close #11698

doc(contributing): add missing donation link

---

src/core/vdom/create-component.js

Fixes https://github.com/vuejs/vue/issues/11703

build: unexpected token when running dev

---

package.json

chore: fix npm test on Windows

---

yarn.lock

chore: up yarn.lock

---

types/vue.d.ts

**Other information:** See https://github.com/vuejs/vue/blob/v2.6.12/src/core/util/debug.js#L18-L26

fix(types): add types for `Vue.util.warn` function

---

types/vnode.d.ts

fix(types): allow symbol &  boolean for vnode key

---

README.md

chore: fix README.md

---

test/ssr/ssr-basic-renderer.spec.js
test/unit/features/component/component-scoped-slot.spec.js
test/unit/features/directives/on.spec.js

- [ x] Other, please describe: typo fix
- [ x] No
- [x ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup

chore: fix typo in  test

---

src/shared/util.js

chore: comment typo [skip ci]

---

test/unit/features/global-api/set-delete.spec.js

chore: fix typo (#12360) [skip ci]

---

packages/weex-template-compiler/build.js

chore: typo [skip ci]

---

scripts/build.js

`packages/compiler-sfc/dist` does not exist by default, resulting in an error in the build.
```sh
npm run build
[Error: ENOENT: no such file or directory, open '/Users/atom/Desktop/github-lib/vue/packages/compiler-sfc/dist/compiler-sfc.js'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/Users/atom/Desktop/github-lib/vue/packages/compiler-sfc/dist/compiler-sfc.js'
}
```

fix: no such file or directory `compiler-sfc/dist`

---

src/core/observer/index.ts

fix: shallow reactive will unwrap refs (#12597)

---

src/v3/apiWatch.ts

chore(types): remove unnecessary type assertion

---

types/tsconfig.json
types/vue.d.ts

I didn't investigate why vue's tsconfig incorrectly resolves an absolute reference to v3-component-public-instance, so I was unable to start with a failing test.

fix #12666: vue.d.ts: Relativise to v3-component-public-instance

---

types/index.d.ts

This PR exports the types for `defineAsyncComponent` that were previously pending. See https://github.com/vuejs/vue/issues/12608#issuecomment-1180484550.

fix(types): export `defineAsyncComponent` type

---

README.md
src/core/instance/proxy.ts
src/core/instance/state.ts

> Fix some broken links inside warnings.
> Should not affect testing.

chore: fix some legacy doc urls in warnings and readme

---

types/options.d.ts

1. No need for updated tests, if it compiles with TS 4.8.
2. Submitted against main branch; I think the dev branch is actually oodate.
Fixes #12753

fix(12753): Add missing type parameter constraints

---

src/core/instance/lifecycle.ts
test/unit/modules/vdom/patch/edge-cases.spec.ts

Fixes [#12589](https://github.com/vuejs/vue/issues/12589)

fix(12589): fix parents HOC $el not update when component update

---

types/jsx.d.ts
types/test/v3/tsx-test.tsx
types/vnode.d.ts

Fix [#12758](https://github.com/vuejs/vue/issues/)

feat(types): add  type  in ReservedProps

---

types/options.d.ts
types/test/options-test.ts

fix(types): fix error with options watch

---

src/core/observer/traverse.ts

fix(watch): avoid traversing objects that are marked non-reactive

---

.github/PULL_REQUEST_TEMPLATE.md

Update the dev to main in the PR template

---

types/common.d.ts

chore: comment typos

---

src/v3/apiAsyncComponent.ts

Fixing a typo in the warning message: suspensiblbe -> suspensible

chore: fix typo in apiAsyncComponent.ts

---

src/types/utils.ts

chore: fix typo in utils.ts (#12927) [skip ci]

---

test/unit/modules/compiler/parser.spec.ts
types/test/async-component-test.ts

chore: fixed some typos

---

src/shared/util.ts

- remove `as` statement and replace by `generic` reducer
- remove brackets from reducer to make it clear and inline pretty

refactor(shared): update `genStaticKeys`

---

types/test/setup-helpers-test.ts
types/v3-setup-helpers.d.ts

Be align with [Vue3 #6764](https://github.com/vuejs/core/pull/6764)

fix(sfc/types): improve the type inference using `withDefaults`

---

packages/compiler-sfc/src/compileScript.ts
packages/compiler-sfc/test/__snapshots__/compileScript.spec.ts.snap
packages/compiler-sfc/test/compileScript.spec.ts

fix(compiler-sfc): Optimize the value of emitIdentifier

---

packages/compiler-sfc/src/compileScript.ts

Be align with Vue3 [#6652](https://github.com/vuejs/core/pull/6652)

fix(compiler-sfc): resolve object expression parsing errors in `v-on`

---

types/vnode.d.ts

- [x ] No
- [x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

fix: type VNodeChildren supports type number 

---

packages/template-compiler/README.md

chore: fix link broken
